import type { ItemNameLexicon } from './types';

// English item-naming lexicon. Names mirror the strings previously held on
// EquipmentTemplate.name / Modifier.name; centralizing them here makes the
// templates language-neutral. Adding a new locale is one new file in this
// directory.

export const lexiconEn: ItemNameLexicon = {
	templateNames: {
		// swords
		sword_t1: "Iron Sword",
		sword_t2: "Copper Blade",
		sword_t3: "Bronze Falchion",
		sword_t4: "Steel Sword",
		sword_t5: "War Blade",
		sword_t6: "Soldier's Sabre",
		sword_t7: "Knight's Edge",
		sword_t8: "Damascus Blade",
		sword_t9: "Warden Sword",
		sword_t10: "Champion Sabre",
		sword_t11: "Templar Blade",
		sword_t12: "Relic Sword",
		sword_t13: "Runed Falchion",
		sword_t14: "Hallowed Edge",
		sword_t15: "Exalted Sabre",
		sword_t16: "Archon Blade",
		sword_t17: "Sovereign Sword",
		sword_t18: "Eternal Falchion",
		sword_t19: "Ascendant Edge",
		sword_t20: "Celestial Sabre",
		sword_t21: "Void-Touched Sabre",
		// daggers
		dagger_t1: "Iron Dagger",
		dagger_t2: "Copper Shiv",
		dagger_t3: "Bronze Stiletto",
		dagger_t4: "Steel Dagger",
		dagger_t5: "War Knife",
		dagger_t6: "Soldier's Dirk",
		dagger_t7: "Knight's Stiletto",
		dagger_t8: "Damascus Dagger",
		dagger_t9: "Warden Shiv",
		dagger_t10: "Champion Dagger",
		dagger_t11: "Templar Dirk",
		dagger_t12: "Relic Stiletto",
		dagger_t13: "Runed Shiv",
		dagger_t14: "Hallowed Dagger",
		dagger_t15: "Exalted Dirk",
		dagger_t16: "Archon Stiletto",
		dagger_t17: "Sovereign Dagger",
		dagger_t18: "Eternal Shiv",
		dagger_t19: "Ascendant Dirk",
		dagger_t20: "Celestial Dagger",
		dagger_t21: "Void-Touched Dagger",
		// axes
		axe_t1: "Iron Axe",
		axe_t2: "Copper Hatchet",
		axe_t3: "Bronze Axe",
		axe_t4: "Steel Hatchet",
		axe_t5: "War Axe",
		axe_t6: "Soldier's Cleaver",
		axe_t7: "Knight's Axe",
		axe_t8: "Damascus Hatchet",
		axe_t9: "Warden Axe",
		axe_t10: "Champion Cleaver",
		axe_t11: "Templar Axe",
		axe_t12: "Relic Hatchet",
		axe_t13: "Runed Axe",
		axe_t14: "Hallowed Cleaver",
		axe_t15: "Exalted Axe",
		axe_t16: "Archon Hatchet",
		axe_t17: "Sovereign Axe",
		axe_t18: "Eternal Cleaver",
		axe_t19: "Ascendant Axe",
		axe_t20: "Celestial Hatchet",
		axe_t21: "Void-Touched Axe",
		// maces
		mace_t1: "Iron Mace",
		mace_t2: "Copper Flail",
		mace_t3: "Bronze Mace",
		mace_t4: "Steel Flail",
		mace_t5: "War Mace",
		mace_t6: "Soldier's Morning Star",
		mace_t7: "Knight's Mace",
		mace_t8: "Damascus Flail",
		mace_t9: "Warden Mace",
		mace_t10: "Champion Morning Star",
		mace_t11: "Templar Mace",
		mace_t12: "Relic Flail",
		mace_t13: "Runed Mace",
		mace_t14: "Hallowed Morning Star",
		mace_t15: "Exalted Mace",
		mace_t16: "Archon Flail",
		mace_t17: "Sovereign Mace",
		mace_t18: "Eternal Morning Star",
		mace_t19: "Ascendant Mace",
		mace_t20: "Celestial Flail",
		mace_t21: "Void-Touched Mace",
		// greatswords
		greatsword_t1: "Iron Greatsword",
		greatsword_t2: "Copper Claymore",
		greatsword_t3: "Bronze Zweihander",
		greatsword_t4: "Steel Greatsword",
		greatsword_t5: "War Claymore",
		greatsword_t6: "Soldier's Greatsword",
		greatsword_t7: "Knight's Claymore",
		greatsword_t8: "Damascus Greatsword",
		greatsword_t9: "Warden Claymore",
		greatsword_t10: "Champion Greatsword",
		greatsword_t11: "Templar Zweihander",
		greatsword_t12: "Relic Greatsword",
		greatsword_t13: "Runed Claymore",
		greatsword_t14: "Hallowed Greatsword",
		greatsword_t15: "Exalted Claymore",
		greatsword_t16: "Archon Greatsword",
		greatsword_t17: "Sovereign Zweihander",
		greatsword_t18: "Eternal Greatsword",
		greatsword_t19: "Ascendant Claymore",
		greatsword_t20: "Celestial Greatsword",
		greatsword_t21: "Void-Touched Greatsword",
		// two-handed-axes
		twoHandedAxe_t1: "Iron Greataxe",
		twoHandedAxe_t2: "Copper Battleaxe",
		twoHandedAxe_t3: "Bronze Greataxe",
		twoHandedAxe_t4: "Steel Battleaxe",
		twoHandedAxe_t5: "War Greataxe",
		twoHandedAxe_t6: "Soldier's Battleaxe",
		twoHandedAxe_t7: "Knight's Greataxe",
		twoHandedAxe_t8: "Damascus Battleaxe",
		twoHandedAxe_t9: "Warden Greataxe",
		twoHandedAxe_t10: "Champion Battleaxe",
		twoHandedAxe_t11: "Templar Greataxe",
		twoHandedAxe_t12: "Relic Battleaxe",
		twoHandedAxe_t13: "Runed Greataxe",
		twoHandedAxe_t14: "Hallowed Battleaxe",
		twoHandedAxe_t15: "Exalted Greataxe",
		twoHandedAxe_t16: "Archon Battleaxe",
		twoHandedAxe_t17: "Sovereign Greataxe",
		twoHandedAxe_t18: "Eternal Battleaxe",
		twoHandedAxe_t19: "Ascendant Greataxe",
		twoHandedAxe_t20: "Celestial Battleaxe",
		twoHandedAxe_t21: "Void-Touched Greataxe",
		// bows
		bow_t1: "Oak Bow",
		bow_t2: "Ash Shortbow",
		bow_t3: "Elm Longbow",
		bow_t4: "Yew Bow",
		bow_t5: "Maple Warbow",
		bow_t6: "Ironbark Bow",
		bow_t7: "Recurve Bow",
		bow_t8: "Composite Bow",
		bow_t9: "Warden Longbow",
		bow_t10: "Champion Bow",
		bow_t11: "Templar Bow",
		bow_t12: "Relic Warbow",
		bow_t13: "Runed Longbow",
		bow_t14: "Hallowed Bow",
		bow_t15: "Exalted Warbow",
		bow_t16: "Archon Bow",
		bow_t17: "Sovereign Longbow",
		bow_t18: "Eternal Bow",
		bow_t19: "Ascendant Warbow",
		bow_t20: "Celestial Bow",
		bow_t21: "Void-Touched Bow",
		// wands
		wand_t1: "Apprentice Wand",
		wand_t2: "Acolyte Wand",
		wand_t3: "Scholar's Wand",
		wand_t4: "Mystic Wand",
		wand_t5: "Invoker's Wand",
		wand_t6: "Channeler's Wand",
		wand_t7: "Conjurer's Wand",
		wand_t8: "Sage Wand",
		wand_t9: "Warden Wand",
		wand_t10: "Oracle Wand",
		wand_t11: "Templar Wand",
		wand_t12: "Relic Wand",
		wand_t13: "Runed Wand",
		wand_t14: "Hallowed Wand",
		wand_t15: "Exalted Wand",
		wand_t16: "Archon Wand",
		wand_t17: "Sovereign Wand",
		wand_t18: "Eternal Wand",
		wand_t19: "Ascendant Wand",
		wand_t20: "Celestial Wand",
		wand_t21: "Void-Touched Wand",
		// staves
		staff_t1: "Apprentice Staff",
		staff_t2: "Acolyte Staff",
		staff_t3: "Scholar's Staff",
		staff_t4: "Mystic Staff",
		staff_t5: "Invoker's Staff",
		staff_t6: "Channeler's Staff",
		staff_t7: "Conjurer's Staff",
		staff_t8: "Sage Staff",
		staff_t9: "Warden Staff",
		staff_t10: "Oracle Staff",
		staff_t11: "Templar Staff",
		staff_t12: "Relic Staff",
		staff_t13: "Runed Staff",
		staff_t14: "Hallowed Staff",
		staff_t15: "Exalted Staff",
		staff_t16: "Archon Staff",
		staff_t17: "Sovereign Staff",
		staff_t18: "Eternal Staff",
		staff_t19: "Ascendant Staff",
		staff_t20: "Celestial Staff",
		staff_t21: "Void-Touched Staff",
		// helmets
		plate_helmet_t1: "Iron Plate Helm",
		plate_helmet_t2: "Copper Plate Helm",
		plate_helmet_t3: "Bronze Plate Helm",
		plate_helmet_t4: "Steel Plate Helm",
		plate_helmet_t5: "War Plate Helm",
		plate_helmet_t6: "Soldier's Plate Helm",
		plate_helmet_t7: "Knight's Plate Helm",
		plate_helmet_t8: "Damascus Plate Helm",
		plate_helmet_t9: "Warden Plate Helm",
		plate_helmet_t10: "Champion Plate Helm",
		plate_helmet_t11: "Templar Plate Helm",
		plate_helmet_t12: "Relic Plate Helm",
		plate_helmet_t13: "Runed Plate Helm",
		plate_helmet_t14: "Hallowed Plate Helm",
		plate_helmet_t15: "Exalted Plate Helm",
		plate_helmet_t16: "Archon Plate Helm",
		plate_helmet_t17: "Sovereign Plate Helm",
		plate_helmet_t18: "Eternal Plate Helm",
		plate_helmet_t19: "Ascendant Plate Helm",
		plate_helmet_t20: "Celestial Plate Helm",
		plate_helmet_t21: "Void-Forged Plate Helm",
		leather_helmet_t1: "Rawhide Hood",
		leather_helmet_t2: "Tanned Hood",
		leather_helmet_t3: "Cured Hood",
		leather_helmet_t4: "Studded Hood",
		leather_helmet_t5: "Hardened Hood",
		leather_helmet_t6: "Ranger's Hood",
		leather_helmet_t7: "Scout's Hood",
		leather_helmet_t8: "Treated Hood",
		leather_helmet_t9: "Warden Hood",
		leather_helmet_t10: "Champion Hood",
		leather_helmet_t11: "Templar Hood",
		leather_helmet_t12: "Relic Hood",
		leather_helmet_t13: "Runed Hood",
		leather_helmet_t14: "Hallowed Hood",
		leather_helmet_t15: "Exalted Hood",
		leather_helmet_t16: "Archon Hood",
		leather_helmet_t17: "Sovereign Hood",
		leather_helmet_t18: "Eternal Hood",
		leather_helmet_t19: "Ascendant Hood",
		leather_helmet_t20: "Celestial Hood",
		leather_helmet_t21: "Void-Touched Leather Hood",
		silk_helmet_t1: "Linen Hood",
		silk_helmet_t2: "Cotton Hood",
		silk_helmet_t3: "Woven Hood",
		silk_helmet_t4: "Fine Hood",
		silk_helmet_t5: "Enchanted Hood",
		silk_helmet_t6: "Mystic Hood",
		silk_helmet_t7: "Arcane Hood",
		silk_helmet_t8: "Sage Hood",
		silk_helmet_t9: "Warden Hood",
		silk_helmet_t10: "Oracle Hood",
		silk_helmet_t11: "Templar Hood",
		silk_helmet_t12: "Relic Hood",
		silk_helmet_t13: "Runed Hood",
		silk_helmet_t14: "Hallowed Hood",
		silk_helmet_t15: "Exalted Hood",
		silk_helmet_t16: "Archon Hood",
		silk_helmet_t17: "Sovereign Hood",
		silk_helmet_t18: "Eternal Hood",
		silk_helmet_t19: "Ascendant Hood",
		silk_helmet_t20: "Celestial Hood",
		silk_helmet_t21: "Void-Woven Silk Hood",
		// chestplates
		plate_chestplate_t1: "Iron Plate Armor",
		plate_chestplate_t2: "Copper Plate Armor",
		plate_chestplate_t3: "Bronze Plate Armor",
		plate_chestplate_t4: "Steel Plate Armor",
		plate_chestplate_t5: "War Plate Armor",
		plate_chestplate_t6: "Soldier's Plate Armor",
		plate_chestplate_t7: "Knight's Plate Armor",
		plate_chestplate_t8: "Damascus Plate Armor",
		plate_chestplate_t9: "Warden Plate Armor",
		plate_chestplate_t10: "Champion Plate Armor",
		plate_chestplate_t11: "Templar Plate Armor",
		plate_chestplate_t12: "Relic Plate Armor",
		plate_chestplate_t13: "Runed Plate Armor",
		plate_chestplate_t14: "Hallowed Plate Armor",
		plate_chestplate_t15: "Exalted Plate Armor",
		plate_chestplate_t16: "Archon Plate Armor",
		plate_chestplate_t17: "Sovereign Plate Armor",
		plate_chestplate_t18: "Eternal Plate Armor",
		plate_chestplate_t19: "Ascendant Plate Armor",
		plate_chestplate_t20: "Celestial Plate Armor",
		plate_chestplate_t21: "Void-Forged Plate Armor",
		leather_chestplate_t1: "Rawhide Vest",
		leather_chestplate_t2: "Tanned Vest",
		leather_chestplate_t3: "Cured Vest",
		leather_chestplate_t4: "Studded Vest",
		leather_chestplate_t5: "Hardened Vest",
		leather_chestplate_t6: "Ranger's Vest",
		leather_chestplate_t7: "Scout's Vest",
		leather_chestplate_t8: "Treated Vest",
		leather_chestplate_t9: "Warden Vest",
		leather_chestplate_t10: "Champion Vest",
		leather_chestplate_t11: "Templar Vest",
		leather_chestplate_t12: "Relic Vest",
		leather_chestplate_t13: "Runed Vest",
		leather_chestplate_t14: "Hallowed Vest",
		leather_chestplate_t15: "Exalted Vest",
		leather_chestplate_t16: "Archon Vest",
		leather_chestplate_t17: "Sovereign Vest",
		leather_chestplate_t18: "Eternal Vest",
		leather_chestplate_t19: "Ascendant Vest",
		leather_chestplate_t20: "Celestial Vest",
		leather_chestplate_t21: "Void-Touched Leather Vest",
		silk_chestplate_t1: "Linen Robe",
		silk_chestplate_t2: "Cotton Robe",
		silk_chestplate_t3: "Woven Robe",
		silk_chestplate_t4: "Fine Robe",
		silk_chestplate_t5: "Enchanted Robe",
		silk_chestplate_t6: "Mystic Robe",
		silk_chestplate_t7: "Arcane Robe",
		silk_chestplate_t8: "Sage Robe",
		silk_chestplate_t9: "Warden Robe",
		silk_chestplate_t10: "Oracle Robe",
		silk_chestplate_t11: "Templar Robe",
		silk_chestplate_t12: "Relic Robe",
		silk_chestplate_t13: "Runed Robe",
		silk_chestplate_t14: "Hallowed Robe",
		silk_chestplate_t15: "Exalted Robe",
		silk_chestplate_t16: "Archon Robe",
		silk_chestplate_t17: "Sovereign Robe",
		silk_chestplate_t18: "Eternal Robe",
		silk_chestplate_t19: "Ascendant Robe",
		silk_chestplate_t20: "Celestial Robe",
		silk_chestplate_t21: "Void-Woven Silk Robe",
		// boots
		plate_boots_t1: "Iron Plate Boots",
		plate_boots_t2: "Copper Plate Boots",
		plate_boots_t3: "Bronze Plate Boots",
		plate_boots_t4: "Steel Plate Boots",
		plate_boots_t5: "War Plate Boots",
		plate_boots_t6: "Soldier's Plate Boots",
		plate_boots_t7: "Knight's Plate Boots",
		plate_boots_t8: "Damascus Plate Boots",
		plate_boots_t9: "Warden Plate Boots",
		plate_boots_t10: "Champion Plate Boots",
		plate_boots_t11: "Templar Plate Boots",
		plate_boots_t12: "Relic Plate Boots",
		plate_boots_t13: "Runed Plate Boots",
		plate_boots_t14: "Hallowed Plate Boots",
		plate_boots_t15: "Exalted Plate Boots",
		plate_boots_t16: "Archon Plate Boots",
		plate_boots_t17: "Sovereign Plate Boots",
		plate_boots_t18: "Eternal Plate Boots",
		plate_boots_t19: "Ascendant Plate Boots",
		plate_boots_t20: "Celestial Plate Boots",
		plate_boots_t21: "Void-Forged Plate Boots",
		leather_boots_t1: "Rawhide Boots",
		leather_boots_t2: "Tanned Boots",
		leather_boots_t3: "Cured Boots",
		leather_boots_t4: "Studded Boots",
		leather_boots_t5: "Hardened Boots",
		leather_boots_t6: "Ranger's Boots",
		leather_boots_t7: "Scout's Boots",
		leather_boots_t8: "Treated Boots",
		leather_boots_t9: "Warden Boots",
		leather_boots_t10: "Champion Boots",
		leather_boots_t11: "Templar Boots",
		leather_boots_t12: "Relic Boots",
		leather_boots_t13: "Runed Boots",
		leather_boots_t14: "Hallowed Boots",
		leather_boots_t15: "Exalted Boots",
		leather_boots_t16: "Archon Boots",
		leather_boots_t17: "Sovereign Boots",
		leather_boots_t18: "Eternal Boots",
		leather_boots_t19: "Ascendant Boots",
		leather_boots_t20: "Celestial Boots",
		leather_boots_t21: "Void-Touched Leather Boots",
		silk_boots_t1: "Linen Slippers",
		silk_boots_t2: "Cotton Slippers",
		silk_boots_t3: "Woven Slippers",
		silk_boots_t4: "Fine Slippers",
		silk_boots_t5: "Enchanted Slippers",
		silk_boots_t6: "Mystic Slippers",
		silk_boots_t7: "Arcane Slippers",
		silk_boots_t8: "Sage Slippers",
		silk_boots_t9: "Warden Slippers",
		silk_boots_t10: "Oracle Slippers",
		silk_boots_t11: "Templar Slippers",
		silk_boots_t12: "Relic Slippers",
		silk_boots_t13: "Runed Slippers",
		silk_boots_t14: "Hallowed Slippers",
		silk_boots_t15: "Exalted Slippers",
		silk_boots_t16: "Archon Slippers",
		silk_boots_t17: "Sovereign Slippers",
		silk_boots_t18: "Eternal Slippers",
		silk_boots_t19: "Ascendant Slippers",
		silk_boots_t20: "Celestial Slippers",
		silk_boots_t21: "Void-Woven Silk Slippers",
		// gloves
		plate_gloves_t1: "Iron Plate Gauntlets",
		plate_gloves_t2: "Copper Plate Gauntlets",
		plate_gloves_t3: "Bronze Plate Gauntlets",
		plate_gloves_t4: "Steel Plate Gauntlets",
		plate_gloves_t5: "War Plate Gauntlets",
		plate_gloves_t6: "Soldier's Plate Gauntlets",
		plate_gloves_t7: "Knight's Plate Gauntlets",
		plate_gloves_t8: "Damascus Plate Gauntlets",
		plate_gloves_t9: "Warden Plate Gauntlets",
		plate_gloves_t10: "Champion Plate Gauntlets",
		plate_gloves_t11: "Templar Plate Gauntlets",
		plate_gloves_t12: "Relic Plate Gauntlets",
		plate_gloves_t13: "Runed Plate Gauntlets",
		plate_gloves_t14: "Hallowed Plate Gauntlets",
		plate_gloves_t15: "Exalted Plate Gauntlets",
		plate_gloves_t16: "Archon Plate Gauntlets",
		plate_gloves_t17: "Sovereign Plate Gauntlets",
		plate_gloves_t18: "Eternal Plate Gauntlets",
		plate_gloves_t19: "Ascendant Plate Gauntlets",
		plate_gloves_t20: "Celestial Plate Gauntlets",
		plate_gloves_t21: "Void-Forged Plate Gauntlets",
		leather_gloves_t1: "Rawhide Gloves",
		leather_gloves_t2: "Tanned Gloves",
		leather_gloves_t3: "Cured Gloves",
		leather_gloves_t4: "Studded Gloves",
		leather_gloves_t5: "Hardened Gloves",
		leather_gloves_t6: "Ranger's Gloves",
		leather_gloves_t7: "Scout's Gloves",
		leather_gloves_t8: "Treated Gloves",
		leather_gloves_t9: "Warden Gloves",
		leather_gloves_t10: "Champion Gloves",
		leather_gloves_t11: "Templar Gloves",
		leather_gloves_t12: "Relic Gloves",
		leather_gloves_t13: "Runed Gloves",
		leather_gloves_t14: "Hallowed Gloves",
		leather_gloves_t15: "Exalted Gloves",
		leather_gloves_t16: "Archon Gloves",
		leather_gloves_t17: "Sovereign Gloves",
		leather_gloves_t18: "Eternal Gloves",
		leather_gloves_t19: "Ascendant Gloves",
		leather_gloves_t20: "Celestial Gloves",
		leather_gloves_t21: "Void-Touched Leather Gloves",
		silk_gloves_t1: "Linen Wraps",
		silk_gloves_t2: "Cotton Wraps",
		silk_gloves_t3: "Woven Wraps",
		silk_gloves_t4: "Fine Wraps",
		silk_gloves_t5: "Enchanted Wraps",
		silk_gloves_t6: "Mystic Wraps",
		silk_gloves_t7: "Arcane Wraps",
		silk_gloves_t8: "Sage Wraps",
		silk_gloves_t9: "Warden Wraps",
		silk_gloves_t10: "Oracle Wraps",
		silk_gloves_t11: "Templar Wraps",
		silk_gloves_t12: "Relic Wraps",
		silk_gloves_t13: "Runed Wraps",
		silk_gloves_t14: "Hallowed Wraps",
		silk_gloves_t15: "Exalted Wraps",
		silk_gloves_t16: "Archon Wraps",
		silk_gloves_t17: "Sovereign Wraps",
		silk_gloves_t18: "Eternal Wraps",
		silk_gloves_t19: "Ascendant Wraps",
		silk_gloves_t20: "Celestial Wraps",
		silk_gloves_t21: "Void-Woven Silk Wraps",
		// shields
		plate_shield_t1: "Iron Tower Shield",
		plate_shield_t2: "Copper Tower Shield",
		plate_shield_t3: "Bronze Tower Shield",
		plate_shield_t4: "Steel Tower Shield",
		plate_shield_t5: "War Tower Shield",
		plate_shield_t6: "Soldier's Tower Shield",
		plate_shield_t7: "Knight's Tower Shield",
		plate_shield_t8: "Damascus Tower Shield",
		plate_shield_t9: "Warden Tower Shield",
		plate_shield_t10: "Champion Tower Shield",
		plate_shield_t11: "Templar Tower Shield",
		plate_shield_t12: "Relic Tower Shield",
		plate_shield_t13: "Runed Tower Shield",
		plate_shield_t14: "Hallowed Tower Shield",
		plate_shield_t15: "Exalted Tower Shield",
		plate_shield_t16: "Archon Tower Shield",
		plate_shield_t17: "Sovereign Tower Shield",
		plate_shield_t18: "Eternal Tower Shield",
		plate_shield_t19: "Ascendant Tower Shield",
		plate_shield_t20: "Celestial Tower Shield",
		plate_shield_t21: "Void-Forged Tower Shield",
		leather_shield_t1: "Rawhide Buckler",
		leather_shield_t2: "Tanned Buckler",
		leather_shield_t3: "Cured Buckler",
		leather_shield_t4: "Studded Buckler",
		leather_shield_t5: "Hardened Buckler",
		leather_shield_t6: "Ranger's Buckler",
		leather_shield_t7: "Scout's Buckler",
		leather_shield_t8: "Treated Buckler",
		leather_shield_t9: "Warden Buckler",
		leather_shield_t10: "Champion Buckler",
		leather_shield_t11: "Templar Buckler",
		leather_shield_t12: "Relic Buckler",
		leather_shield_t13: "Runed Buckler",
		leather_shield_t14: "Hallowed Buckler",
		leather_shield_t15: "Exalted Buckler",
		leather_shield_t16: "Archon Buckler",
		leather_shield_t17: "Sovereign Buckler",
		leather_shield_t18: "Eternal Buckler",
		leather_shield_t19: "Ascendant Buckler",
		leather_shield_t20: "Celestial Buckler",
		leather_shield_t21: "Void-Touched Buckler",
		silk_shield_t1: "Linen Ward",
		silk_shield_t2: "Cotton Ward",
		silk_shield_t3: "Woven Ward",
		silk_shield_t4: "Fine Ward",
		silk_shield_t5: "Enchanted Ward",
		silk_shield_t6: "Mystic Ward",
		silk_shield_t7: "Arcane Ward",
		silk_shield_t8: "Sage Ward",
		silk_shield_t9: "Oracle Ward",
		silk_shield_t10: "Seer Ward",
		silk_shield_t11: "Templar Ward",
		silk_shield_t12: "Relic Ward",
		silk_shield_t13: "Runed Ward",
		silk_shield_t14: "Hallowed Ward",
		silk_shield_t15: "Exalted Ward",
		silk_shield_t16: "Archon Ward",
		silk_shield_t17: "Sovereign Ward",
		silk_shield_t18: "Eternal Ward",
		silk_shield_t19: "Ascendant Ward",
		silk_shield_t20: "Celestial Ward",
		silk_shield_t21: "Void-Woven Ward",
		// tomes
		tome_t1: "Apprentice Tome",
		tome_t2: "Acolyte Tome",
		tome_t3: "Initiate Tome",
		tome_t4: "Scholar's Tome",
		tome_t5: "Adept Tome",
		tome_t6: "Magister Tome",
		tome_t7: "Mystic Tome",
		tome_t8: "Arcane Tome",
		tome_t9: "Sage Tome",
		tome_t10: "Oracle Tome",
		tome_t11: "Hierophant Tome",
		tome_t12: "Templar Tome",
		tome_t13: "Runed Tome",
		tome_t14: "Hallowed Tome",
		tome_t15: "Exalted Tome",
		tome_t16: "Archon Tome",
		tome_t17: "Sovereign Tome",
		tome_t18: "Eternal Tome",
		tome_t19: "Ascendant Tome",
		tome_t20: "Celestial Tome",
		tome_t21: "Void-Inscribed Tome",
		// quivers
		quiver_t1: "Hide Quiver",
		quiver_t2: "Tanned Quiver",
		quiver_t3: "Hunter's Quiver",
		quiver_t4: "Ranger's Quiver",
		quiver_t5: "Skirmisher Quiver",
		quiver_t6: "Scout's Quiver",
		quiver_t7: "Marksman Quiver",
		quiver_t8: "Treated Quiver",
		quiver_t9: "Warden Quiver",
		quiver_t10: "Champion Quiver",
		quiver_t11: "Templar Quiver",
		quiver_t12: "Relic Quiver",
		quiver_t13: "Runed Quiver",
		quiver_t14: "Hallowed Quiver",
		quiver_t15: "Exalted Quiver",
		quiver_t16: "Archon Quiver",
		quiver_t17: "Sovereign Quiver",
		quiver_t18: "Eternal Quiver",
		quiver_t19: "Ascendant Quiver",
		quiver_t20: "Celestial Quiver",
		quiver_t21: "Void-Touched Quiver",
		// rings
		cobalt_ring: "Cobalt Ring",
		garnet_ring: "Garnet Ring",
		topaz_ring: "Topaz Ring",
		obsidian_ring: "Obsidian Ring",
		coral_ring: "Coral Ring",
		lapis_ring: "Lapis Ring",
		// amulets
		gold_amulet: "Prismatic Amulet",
		jade_amulet: "Jade Amulet",
		amber_amulet: "Amber Amulet",
		lapis_amulet: "Lapis Amulet",
		// belts
		leather_belt: "Leather Belt",
		chain_belt: "Chain Belt",
		studded_belt: "Studded Belt",
		cloth_belt: "Cloth Belt",
		prismatic_belt: "Prismatic Belt",
		silk_belt: "Silk Belt",
	},
	prefixForms: {
		localDefenseFlat: "Reinforced",
		armorFlat: "Sturdy",
		evasionFlat: "Agile",
		barrierFlat: "Warding",
		healthFlat: "Vital",
		manaFlat: "Insightful",
		lifeGainOnHitFlat: "Siphoning",
		manaGainOnHitFlat: "Channeling",
		globalPhysicalDamageIncrease: "Devastating",
		globalColdDamageIncrease: "Frigid",
		globalFireDamageIncrease: "Blazing",
		globalLightningDamageIncrease: "Thunderous",
		globalVoidDamageIncrease: "Abyssal",
		globalSpellDamageIncrease: "Arcane",
		globalElementalDamageWithAttacksIncrease: "Primal",
		globalElementalDamageIncrease: "Elemental",
		globalMeleeDamageIncrease: "Brutal",
		itemRarityIncreasePrefix: "Prosperous",
		coldDamageFlat: "Frosty",
		fireDamageFlat: "Burning",
		lightningDamageFlat: "Shocking",
		voidDamageFlat: "Voidtouched",
		tomeGainAsExtraCold: "Frost-Touched",
		tomeGainAsExtraFire: "Burning-Page",
		tomeGainAsExtraLightning: "Storm-Bound",
		tomeGainAsExtraVoid: "Abyss-Inscribed",
		physicalDamageFlat: "Heavy",
		physicalDamageFlatGlobal: "Heavy",
		physicalDamageIncrease: "Cruel",
		coldDamageToAttacksFlat: "Chilling",
		fireDamageToAttacksFlat: "Scorching",
		lightningDamageToAttacksFlat: "Crackling",
		voidDamageToAttacksFlat: "Voidscarred",
		coldDamageToAttacksFlatGlobal: "Chilling",
		fireDamageToAttacksFlatGlobal: "Scorching",
		lightningDamageToAttacksFlatGlobal: "Crackling",
		voidDamageToAttacksFlatGlobal: "Voidscarred",
	},
	suffixPhrases: {
		strengthFlat: "of Strength",
		dexterityFlat: "of Dexterity",
		intelligenceFlat: "of Intelligence",
		allAttributesFlat: "of All Attributes",
		localDefenseIncrease: "of Fortification",
		globalArmorIncrease: "of Protection",
		globalEvasionIncrease: "of Evasion",
		globalBarrierIncrease: "of Warding",
		healthRegenFlat: "of Regeneration",
		manaRegenFlat: "of Focus",
		lifeOnKillFlat: "of Culling",
		manaOnKillFlat: "of Absorption",
		thornsDamageFlat: "of Thorns",
		blockChanceIncrease: "of Blocking",
		globalAttackSpeedIncrease: "of Haste",
		globalCastSpeedIncrease: "of Casting",
		globalCriticalChanceIncrease: "of Deadliness",
		itemRarityIncreaseSuffix: "of Fortune",
		coldResistance: "of Frost Resistance",
		fireResistance: "of Flame Resistance",
		lightningResistance: "of Storm Resistance",
		voidResistance: "of Void Resistance",
		movementSpeedIncrease: "of Speed",
		lifeLeechPercent: "of Leeching",
		stunDurationIncrease: "of Stunning",
		reducedAttributeRequirements: "of the Worthy",
		attackSpeedIncrease: "of Swiftness",
		criticalChanceIncrease: "of Precision",
		accuracyFlat: "of the Ranger",
		criticalStrikeMultiplierFlat: "of Destruction",
	},
	rareFirstWords: ["Doom", "Storm", "Grim", "Soul", "Death", "Mind", "Dragon", "Eagle", "Phoenix", "Rune", "Viper", "Kraken", "Havoc", "Gale", "Dusk", "Blood", "Shadow", "Wrath", "Spirit", "Blight", "Dread", "Rage", "Spite", "Void", "Plague", "Skull", "Foe", "Bone", "Ash", "Thorn"],
	rareSecondWords: ["Mark", "Shelter", "Bane", "Grasp", "Edge", "Turn", "Song", "Roar", "Call", "Star", "Keep", "Bite", "Wound", "Strike", "Haven", "Gutter", "Knell", "Breaker", "Whisper", "Rend", "Scar", "Pyre", "Reach", "Span", "Coil", "Trail", "Veil", "Crown", "Thirst", "Shatter"],
};
