import type { ItemNameLexicon } from "./types";

// English item-naming lexicon. The decomposed shape lets templates declare a
// (base, modifier) tuple; the renderer composes them as "<modifier> <base>"
// (EN word order). Modifiers don't inflect — every entry is a flat string.

export const lexiconEn: ItemNameLexicon = {
	bases: {
		sword: { name: "Sword" },
		blade: { name: "Blade" },
		falchion: { name: "Falchion" },
		sabre: { name: "Sabre" },
		edge: { name: "Edge" },
		dagger: { name: "Dagger" },
		shiv: { name: "Shiv" },
		stiletto: { name: "Stiletto" },
		knife: { name: "Knife" },
		dirk: { name: "Dirk" },
		axe: { name: "Axe" },
		hatchet: { name: "Hatchet" },
		cleaver: { name: "Cleaver" },
		mace: { name: "Mace" },
		flail: { name: "Flail" },
		greatsword: { name: "Greatsword" },
		claymore: { name: "Claymore" },
		zweihander: { name: "Zweihander" },
		greataxe: { name: "Greataxe" },
		battleaxe: { name: "Battleaxe" },
		bow: { name: "Bow" },
		shortbow: { name: "Shortbow" },
		longbow: { name: "Longbow" },
		warbow: { name: "Warbow" },
		wand: { name: "Wand" },
		staff: { name: "Staff" },
		morning_star: { name: "Morning Star" },
		hood: { name: "Hood" },
		vest: { name: "Vest" },
		boots: { name: "Boots" },
		gloves: { name: "Gloves" },
		robe: { name: "Robe" },
		slippers: { name: "Slippers" },
		wraps: { name: "Wraps" },
		plate_helm: { name: "Plate Helm" },
		plate_armor: { name: "Plate Armor" },
		plate_boots: { name: "Plate Boots" },
		plate_gauntlets: { name: "Plate Gauntlets" },
		tower_shield: { name: "Tower Shield" },
		buckler: { name: "Buckler" },
		ward: { name: "Ward" },
		tome: { name: "Tome" },
		quiver: { name: "Quiver" },
		ring: { name: "Ring" },
		amulet: { name: "Amulet" },
		belt: { name: "Belt" },
		void_touched_leather_hood: { name: "Void-Touched Leather Hood" },
		void_touched_leather_vest: { name: "Void-Touched Leather Vest" },
		void_touched_leather_boots: { name: "Void-Touched Leather Boots" },
		void_touched_leather_gloves: { name: "Void-Touched Leather Gloves" },
		void_touched_buckler: { name: "Void-Touched Buckler" },
		void_woven_silk_hood: { name: "Void-Woven Silk Hood" },
		void_woven_silk_robe: { name: "Void-Woven Silk Robe" },
		void_woven_silk_slippers: { name: "Void-Woven Silk Slippers" },
		void_woven_silk_wraps: { name: "Void-Woven Silk Wraps" },
	},
	modifiers: {
		iron: "Iron",
		copper: "Copper",
		bronze: "Bronze",
		steel: "Steel",
		damascus: "Damascus",
		war: "War",
		soldiers: "Soldier's",
		knights: "Knight's",
		warden: "Warden",
		champion: "Champion",
		templar: "Templar",
		relic: "Relic",
		runed: "Runed",
		hallowed: "Hallowed",
		exalted: "Exalted",
		archon: "Archon",
		sovereign: "Sovereign",
		eternal: "Eternal",
		ascendant: "Ascendant",
		celestial: "Celestial",
		void_touched: "Void-Touched",
		void_forged: "Void-Forged",
		void_inscribed: "Void-Inscribed",
		void_woven: "Void-Woven",
		oak: "Oak",
		ash: "Ash",
		elm: "Elm",
		yew: "Yew",
		maple: "Maple",
		ironbark: "Ironbark",
		recurve: "Recurve",
		composite: "Composite",
		apprentice: "Apprentice",
		acolyte: "Acolyte",
		initiate: "Initiate",
		scholars: "Scholar's",
		adept: "Adept",
		magister: "Magister",
		mystic: "Mystic",
		arcane: "Arcane",
		sage: "Sage",
		oracle: "Oracle",
		hierophant: "Hierophant",
		seer: "Seer",
		invokers: "Invoker's",
		channelers: "Channeler's",
		conjurers: "Conjurer's",
		rawhide: "Rawhide",
		tanned: "Tanned",
		cured: "Cured",
		studded: "Studded",
		hardened: "Hardened",
		rangers: "Ranger's",
		scouts: "Scout's",
		treated: "Treated",
		linen: "Linen",
		cotton: "Cotton",
		woven: "Woven",
		fine: "Fine",
		enchanted: "Enchanted",
		hide: "Hide",
		hunters: "Hunter's",
		skirmisher: "Skirmisher",
		marksman: "Marksman",
		cobalt: "Cobalt",
		garnet: "Garnet",
		topaz: "Topaz",
		obsidian: "Obsidian",
		coral: "Coral",
		lapis: "Lapis",
		gold: "Gold",
		jade: "Jade",
		amber: "Amber",
		prismatic: "Prismatic",
		leather: "Leather",
		chain: "Chain",
		cloth: "Cloth",
		silk: "Silk",
		rusty: "Rusty",
		cracked: "Cracked",
	},
	prefixForms: {
		localDefenseFlat: "Reinforced",
		armorFlat: "Sturdy",
		evasionFlat: "Agile",
		barrierFlat: "Warding",
		healthFlat: "Vital",
		manaFlat: "Insightful",
		lifeGainOnHitFlat: "Siphoning",
		manaGainOnHitFlat: "Channeling",
		globalPhysicalDamageIncrease: "Devastating",
		globalColdDamageIncrease: "Frigid",
		globalFireDamageIncrease: "Blazing",
		globalLightningDamageIncrease: "Thunderous",
		globalVoidDamageIncrease: "Abyssal",
		globalSpellDamageIncrease: "Arcane",
		globalElementalDamageWithAttacksIncrease: "Primal",
		globalElementalDamageIncrease: "Elemental",
		globalMeleeDamageIncrease: "Brutal",
		itemRarityIncreasePrefix: "Prosperous",
		coldDamageFlat: "Frosty",
		fireDamageFlat: "Burning",
		lightningDamageFlat: "Shocking",
		voidDamageFlat: "Voidtouched",
		tomeGainAsExtraCold: "Frost-Touched",
		tomeGainAsExtraFire: "Burning-Page",
		tomeGainAsExtraLightning: "Storm-Bound",
		tomeGainAsExtraVoid: "Abyss-Inscribed",
		physicalDamageFlat: "Heavy",
		physicalDamageFlatGlobal: "Heavy",
		physicalDamageIncrease: "Cruel",
		coldDamageToAttacksFlat: "Chilling",
		fireDamageToAttacksFlat: "Scorching",
		lightningDamageToAttacksFlat: "Crackling",
		voidDamageToAttacksFlat: "Voidscarred",
		coldDamageToAttacksFlatGlobal: "Chilling",
		fireDamageToAttacksFlatGlobal: "Scorching",
		lightningDamageToAttacksFlatGlobal: "Crackling",
		voidDamageToAttacksFlatGlobal: "Voidscarred",
	},
	suffixPhrases: {
		strengthFlat: "of Strength",
		dexterityFlat: "of Dexterity",
		intelligenceFlat: "of Intelligence",
		allAttributesFlat: "of All Attributes",
		localDefenseIncrease: "of Fortification",
		globalArmorIncrease: "of Protection",
		globalEvasionIncrease: "of Evasion",
		globalBarrierIncrease: "of Warding",
		healthRegenFlat: "of Regeneration",
		manaRegenFlat: "of Focus",
		lifeOnKillFlat: "of Culling",
		manaOnKillFlat: "of Absorption",
		thornsDamageFlat: "of Thorns",
		blockChanceIncrease: "of Blocking",
		globalAttackSpeedIncrease: "of Haste",
		globalCastSpeedIncrease: "of Casting",
		globalCriticalChanceIncrease: "of Deadliness",
		itemRarityIncreaseSuffix: "of Fortune",
		coldResistance: "of Frost Resistance",
		fireResistance: "of Flame Resistance",
		lightningResistance: "of Storm Resistance",
		voidResistance: "of Void Resistance",
		movementSpeedIncrease: "of Speed",
		lifeLeechPercent: "of Leeching",
		stunDurationIncrease: "of Stunning",
		reducedAttributeRequirements: "of the Worthy",
		attackSpeedIncrease: "of Swiftness",
		criticalChanceIncrease: "of Precision",
		accuracyFlat: "of the Ranger",
		criticalStrikeMultiplierFlat: "of Destruction",
	},
	rareFirstWords: [
		"Doom",
		"Storm",
		"Grim",
		"Soul",
		"Death",
		"Mind",
		"Dragon",
		"Eagle",
		"Phoenix",
		"Rune",
		"Viper",
		"Kraken",
		"Havoc",
		"Gale",
		"Dusk",
		"Blood",
		"Shadow",
		"Wrath",
		"Spirit",
		"Blight",
		"Dread",
		"Rage",
		"Spite",
		"Void",
		"Plague",
		"Skull",
		"Foe",
		"Bone",
		"Ash",
		"Thorn",
	],
	rareSecondWords: [
		"Mark",
		"Shelter",
		"Bane",
		"Grasp",
		"Edge",
		"Turn",
		"Song",
		"Roar",
		"Call",
		"Star",
		"Keep",
		"Bite",
		"Wound",
		"Strike",
		"Haven",
		"Gutter",
		"Knell",
		"Breaker",
		"Whisper",
		"Rend",
		"Scar",
		"Pyre",
		"Reach",
		"Span",
		"Coil",
		"Trail",
		"Veil",
		"Crown",
		"Thirst",
		"Shatter",
	],
};
