import type { ItemNameLexicon } from "./types";

// Portuguese item-naming lexicon. Bases carry grammatical gender; modifiers
// are either invariant phrases ("de Ferro", "do Soldado") or gendered
// adjectives ("Sagrado/Sagrada") that agree with the base's gender at
// render time. The renderer composes as "<base> <modifier>" (PT word order).

export const lexiconPt: ItemNameLexicon = {
	bases: {
		sword: { name: "Espada", gender: "f" },
		blade: { name: "Lâmina", gender: "f" },
		falchion: { name: "Sabre", gender: "m" },
		sabre: { name: "Sabre", gender: "m" },
		edge: { name: "Gume", gender: "m" },
		dagger: { name: "Adaga", gender: "f" },
		shiv: { name: "Punhal", gender: "m" },
		stiletto: { name: "Estilete", gender: "m" },
		knife: { name: "Faca", gender: "f" },
		dirk: { name: "Adaga Curta", gender: "f" },
		axe: { name: "Machado", gender: "m" },
		hatchet: { name: "Machadinha", gender: "f" },
		cleaver: { name: "Cutelo", gender: "m" },
		mace: { name: "Maça", gender: "f" },
		flail: { name: "Mangual", gender: "m" },
		greatsword: { name: "Espada Bastarda", gender: "f" },
		claymore: { name: "Claymore", gender: "f" },
		zweihander: { name: "Zweihänder", gender: "m" },
		greataxe: { name: "Machadão", gender: "m" },
		battleaxe: { name: "Machado de Batalha", gender: "m" },
		bow: { name: "Arco", gender: "m" },
		shortbow: { name: "Arco Curto", gender: "m" },
		longbow: { name: "Arco Longo", gender: "m" },
		warbow: { name: "Arco de Guerra", gender: "m" },
		wand: { name: "Varinha", gender: "f" },
		staff: { name: "Cajado", gender: "m" },
		morning_star: { name: "Estrela da Manhã", gender: "f" },
		hood: { name: "Capuz", gender: "m" },
		vest: { name: "Colete", gender: "m" },
		boots: { name: "Botas", gender: "f" },
		gloves: { name: "Luvas", gender: "f" },
		robe: { name: "Túnica", gender: "f" },
		slippers: { name: "Sapatilhas", gender: "f" },
		wraps: { name: "Bandagens", gender: "f" },
		plate_helm: { name: "Elmo de Placas", gender: "m" },
		plate_armor: { name: "Peitoral de Placas", gender: "m" },
		plate_boots: { name: "Botas de Placas", gender: "f" },
		plate_gauntlets: { name: "Manoplas", gender: "f" },
		tower_shield: { name: "Escudo de Torre", gender: "m" },
		buckler: { name: "Brocal", gender: "m" },
		ward: { name: "Égide", gender: "f" },
		tome: { name: "Tomo", gender: "m" },
		quiver: { name: "Aljava", gender: "f" },
		ring: { name: "Anel", gender: "m" },
		amulet: { name: "Amuleto", gender: "m" },
		belt: { name: "Cinto", gender: "m" },
		void_touched_leather_hood: { name: "Capuz de Couro", gender: "m" },
		void_touched_leather_vest: { name: "Colete de Couro", gender: "m" },
		void_touched_leather_boots: { name: "Botas de Couro", gender: "f" },
		void_touched_leather_gloves: { name: "Luvas de Couro", gender: "f" },
		void_touched_buckler: { name: "Brocal de Couro", gender: "m" },
		void_woven_silk_hood: { name: "Capuz de Seda", gender: "m" },
		void_woven_silk_robe: { name: "Túnica de Seda", gender: "f" },
		void_woven_silk_slippers: { name: "Sapatilhas de Seda", gender: "f" },
		void_woven_silk_wraps: { name: "Bandagens de Seda", gender: "f" },
	},
	modifiers: {
		iron: "de Ferro",
		copper: "de Cobre",
		bronze: "de Bronze",
		steel: "de Aço",
		damascus: "de Damasco",
		war: "de Guerra",
		soldiers: "do Soldado",
		knights: "do Cavaleiro",
		warden: "do Vigia",
		champion: "do Campeão",
		templar: { m: "Templário", f: "Templária" },
		relic: { m: "Relíquia", f: "Relíquia" },
		runed: { m: "Rúnico", f: "Rúnica" },
		hallowed: { m: "Sagrado", f: "Sagrada" },
		exalted: { m: "Exaltado", f: "Exaltada" },
		archon: "do Arconte",
		sovereign: { m: "Soberano", f: "Soberana" },
		eternal: { m: "Eterno", f: "Eterna" },
		ascendant: { m: "Ascendente", f: "Ascendente" },
		celestial: { m: "Celestial", f: "Celestial" },
		void_touched: { m: "Maculado pelo Vazio", f: "Maculada pelo Vazio" },
		void_forged: { m: "Forjado no Vazio", f: "Forjada no Vazio" },
		void_inscribed: { m: "Inscrito no Vazio", f: "Inscrita no Vazio" },
		void_woven: { m: "Tecido no Vazio", f: "Tecida no Vazio" },
		oak: "de Carvalho",
		ash: "de Freixo",
		elm: "de Olmo",
		yew: "de Teixo",
		maple: "de Bordo",
		ironbark: "de Casca de Ferro",
		recurve: { m: "Recurvo", f: "Recurva" },
		composite: { m: "Composto", f: "Composta" },
		apprentice: "do Aprendiz",
		acolyte: "do Acólito",
		initiate: "do Iniciado",
		scholars: "do Erudito",
		adept: "do Adepto",
		magister: "do Magíster",
		mystic: { m: "Místico", f: "Mística" },
		arcane: { m: "Arcano", f: "Arcana" },
		sage: "do Sábio",
		oracle: "do Oráculo",
		hierophant: "do Hierofante",
		seer: "do Vidente",
		invokers: "do Invocador",
		channelers: "do Canalizador",
		conjurers: "do Conjurador",
		rawhide: "de Couro Cru",
		tanned: { m: "Curtido", f: "Curtida" },
		cured: { m: "Curado", f: "Curada" },
		studded: { m: "Cravejado", f: "Cravejada" },
		hardened: { m: "Endurecido", f: "Endurecida" },
		rangers: "do Patrulheiro",
		scouts: "do Batedor",
		treated: { m: "Tratado", f: "Tratada" },
		linen: "de Linho",
		cotton: "de Algodão",
		woven: { m: "Tecido", f: "Tecida" },
		fine: { m: "Fino", f: "Fina" },
		enchanted: { m: "Encantado", f: "Encantada" },
		hide: "de Couro",
		hunters: "do Caçador",
		skirmisher: "do Escaramuçador",
		marksman: "do Atirador",
		cobalt: "de Cobalto",
		garnet: "de Granada",
		topaz: "de Topázio",
		obsidian: "de Obsidiana",
		coral: "de Coral",
		lapis: "de Lápis",
		gold: "de Ouro",
		jade: "de Jade",
		amber: "de Âmbar",
		prismatic: { m: "Prismático", f: "Prismática" },
		leather: "de Couro",
		chain: "de Correntes",
		cloth: "de Pano",
		silk: "de Seda",
		rusty: { m: "Enferrujado", f: "Enferrujada" },
		cracked: { m: "Rachado", f: "Rachada" },
	},
	prefixForms: {
		localDefenseFlat: { m: "Reforçado", f: "Reforçada" },
		armorFlat: { m: "Robusto", f: "Robusta" },
		evasionFlat: { m: "Ágil", f: "Ágil" },
		barrierFlat: { m: "Protetor", f: "Protetora" },
		healthFlat: { m: "Vital", f: "Vital" },
		manaFlat: { m: "Perspicaz", f: "Perspicaz" },
		lifeGainOnHitFlat: { m: "Sugador", f: "Sugadora" },
		manaGainOnHitFlat: { m: "Canalizador", f: "Canalizadora" },
		globalPhysicalDamageIncrease: { m: "Devastador", f: "Devastadora" },
		globalColdDamageIncrease: { m: "Gélido", f: "Gélida" },
		globalFireDamageIncrease: { m: "Flamejante", f: "Flamejante" },
		globalLightningDamageIncrease: { m: "Trovejante", f: "Trovejante" },
		globalVoidDamageIncrease: { m: "Abissal", f: "Abissal" },
		globalSpellDamageIncrease: { m: "Arcano", f: "Arcana" },
		globalElementalDamageWithAttacksIncrease: { m: "Primal", f: "Primal" },
		globalElementalDamageIncrease: { m: "Elemental", f: "Elemental" },
		globalMeleeDamageIncrease: { m: "Brutal", f: "Brutal" },
		itemRarityIncreasePrefix: { m: "Próspero", f: "Próspera" },
		coldDamageFlat: { m: "Glacial", f: "Glacial" },
		fireDamageFlat: { m: "Ardente", f: "Ardente" },
		lightningDamageFlat: { m: "Eletrizante", f: "Eletrizante" },
		voidDamageFlat: { m: "Tocado pelo Vácuo", f: "Tocada pelo Vácuo" },
		tomeGainAsExtraCold: { m: "Tocado pelo Gelo", f: "Tocada pelo Gelo" },
		tomeGainAsExtraFire: { m: "Página Ardente", f: "Página Ardente" },
		tomeGainAsExtraLightning: {
			m: "Atado à Tempestade",
			f: "Atada à Tempestade",
		},
		tomeGainAsExtraVoid: { m: "Inscrito no Abismo", f: "Inscrita no Abismo" },
		physicalDamageFlat: { m: "Pesado", f: "Pesada" },
		physicalDamageFlatGlobal: { m: "Pesado", f: "Pesada" },
		physicalDamageIncrease: { m: "Cruel", f: "Cruel" },
		coldDamageToAttacksFlat: { m: "Congelante", f: "Congelante" },
		fireDamageToAttacksFlat: { m: "Escaldante", f: "Escaldante" },
		lightningDamageToAttacksFlat: { m: "Crepitante", f: "Crepitante" },
		voidDamageToAttacksFlat: {
			m: "Marcado pelo Vácuo",
			f: "Marcada pelo Vácuo",
		},
		coldDamageToAttacksFlatGlobal: { m: "Congelante", f: "Congelante" },
		fireDamageToAttacksFlatGlobal: { m: "Escaldante", f: "Escaldante" },
		lightningDamageToAttacksFlatGlobal: { m: "Crepitante", f: "Crepitante" },
		voidDamageToAttacksFlatGlobal: {
			m: "Marcado pelo Vácuo",
			f: "Marcada pelo Vácuo",
		},
	},
	suffixPhrases: {
		strengthFlat: "da Força",
		dexterityFlat: "da Destreza",
		intelligenceFlat: "da Inteligência",
		allAttributesFlat: "de Todos os Atributos",
		localDefenseIncrease: "da Fortificação",
		globalArmorIncrease: "da Proteção",
		globalEvasionIncrease: "da Esquiva",
		globalBarrierIncrease: "da Salvaguarda",
		healthRegenFlat: "da Regeneração",
		manaRegenFlat: "do Foco",
		lifeOnKillFlat: "do Ceifar",
		manaOnKillFlat: "da Absorção",
		thornsDamageFlat: "dos Espinhos",
		blockChanceIncrease: "do Bloqueio",
		globalAttackSpeedIncrease: "da Pressa",
		globalCastSpeedIncrease: "da Conjuração",
		globalCriticalChanceIncrease: "da Letalidade",
		itemRarityIncreaseSuffix: "da Fortuna",
		coldResistance: "da Resistência ao Frio",
		fireResistance: "da Resistência ao Fogo",
		lightningResistance: "da Resistência ao Raio",
		voidResistance: "da Resistência ao Vácuo",
		movementSpeedIncrease: "da Velocidade",
		lifeLeechPercent: "do Roubo de Vida",
		stunDurationIncrease: "do Atordoamento",
		reducedAttributeRequirements: "do Digno",
		attackSpeedIncrease: "da Rapidez",
		criticalChanceIncrease: "da Precisão",
		accuracyFlat: "do Patrulheiro",
		criticalStrikeMultiplierFlat: "da Destruição",
	},
	rareFirstWords: [
		"Lâmina",
		"Coroa",
		"Marca",
		"Garra",
		"Ruína",
		"Tempestade",
		"Sombra",
		"Cinzas",
		"Fúria",
		"Pavor",
		"Vazio",
		"Destino",
		"Alma",
		"Morte",
		"Lúgubre",
		"Mente",
		"Dragão",
		"Águia",
		"Fênix",
		"Runa",
		"Víbora",
		"Kraken",
		"Estrago",
		"Vendaval",
		"Crepúsculo",
		"Sangue",
		"Ira",
		"Espírito",
		"Praga",
		"Espinho",
	],
	rareSecondWords: [
		"da Tempestade",
		"do Vazio",
		"das Sombras",
		"do Dragão",
		"da Praga",
		"da Ruína",
		"do Sangue",
		"do Crepúsculo",
		"da Fúria",
		"do Abismo",
		"da Morte",
		"do Trovão",
		"da Lâmina",
		"das Cinzas",
		"do Espírito",
		"do Caçador",
		"da Águia",
		"do Lobo",
		"da Serpente",
		"da Coroa",
		"do Vento",
		"da Aurora",
		"do Ocaso",
		"do Pavor",
		"do Inverno",
		"do Vulcão",
		"da Noite",
		"da Estrela",
		"do Ferro",
		"da Tormenta",
	],
};
