import type { ItemNameLexicon } from "./types";

// Portuguese item-naming lexicon. PT puts the adjective AFTER the noun and
// agrees with the template noun's grammatical gender. Suffix phrases anchor
// to their own noun ("da Rapidez" — Rapidez is feminine intrinsically) so
// they don't need template-gender concord.
//
// Translation strategy:
//   - Material modifiers (Iron, Copper, etc.) become "de Ferro" / "de Cobre"
//   - Owner modifiers (Soldier's, Warden, etc.) become "do Soldado" / "do Vigia"
//   - Adjective modifiers (Runed, Hallowed, etc.) inflect: "Rúnico/Rúnica",
//     "Sagrado/Sagrada"
//
// Composition order in the renderer: `${base} ${adjectives} ${phrases}`.

export const lexiconPt: ItemNameLexicon = {
	templateNames: {
		// swords
		sword_t1: "Espada de Ferro",
		sword_t2: "Lâmina de Cobre",
		sword_t3: "Sabre de Bronze",
		sword_t4: "Espada de Aço",
		sword_t5: "Lâmina de Guerra",
		sword_t6: "Sabre do Soldado",
		sword_t7: "Lâmina do Cavaleiro",
		sword_t8: "Lâmina de Damasco",
		sword_t9: "Espada do Vigia",
		sword_t10: "Sabre do Campeão",
		sword_t11: "Lâmina Templária",
		sword_t12: "Espada Relíquia",
		sword_t13: "Sabre Rúnico",
		sword_t14: "Lâmina Sagrada",
		sword_t15: "Sabre Exaltado",
		sword_t16: "Lâmina do Arconte",
		sword_t17: "Espada Soberana",
		sword_t18: "Sabre Eterno",
		sword_t19: "Lâmina Ascendente",
		sword_t20: "Sabre Celestial",
		sword_t21: "Sabre do Vazio",
		// daggers
		dagger_t1: "Adaga de Ferro",
		dagger_t2: "Punhal de Cobre",
		dagger_t3: "Estilete de Bronze",
		dagger_t4: "Adaga de Aço",
		dagger_t5: "Faca de Guerra",
		dagger_t6: "Adaga Curta do Soldado",
		dagger_t7: "Estilete do Cavaleiro",
		dagger_t8: "Adaga de Damasco",
		dagger_t9: "Punhal do Vigia",
		dagger_t10: "Adaga do Campeão",
		dagger_t11: "Adaga Curta Templária",
		dagger_t12: "Estilete Relíquia",
		dagger_t13: "Punhal Rúnico",
		dagger_t14: "Adaga Sagrada",
		dagger_t15: "Adaga Curta Exaltada",
		dagger_t16: "Estilete do Arconte",
		dagger_t17: "Adaga Soberana",
		dagger_t18: "Punhal Eterno",
		dagger_t19: "Adaga Curta Ascendente",
		dagger_t20: "Adaga Celestial",
		dagger_t21: "Adaga do Vazio",
		// axes
		axe_t1: "Machado de Ferro",
		axe_t2: "Machadinha de Cobre",
		axe_t3: "Machado de Bronze",
		axe_t4: "Machadinha de Aço",
		axe_t5: "Machado de Guerra",
		axe_t6: "Cutelo do Soldado",
		axe_t7: "Machado do Cavaleiro",
		axe_t8: "Machadinha de Damasco",
		axe_t9: "Machado do Vigia",
		axe_t10: "Cutelo do Campeão",
		axe_t11: "Machado Templário",
		axe_t12: "Machadinha Relíquia",
		axe_t13: "Machado Rúnico",
		axe_t14: "Cutelo Sagrado",
		axe_t15: "Machado Exaltado",
		axe_t16: "Machadinha do Arconte",
		axe_t17: "Machado Soberano",
		axe_t18: "Cutelo Eterno",
		axe_t19: "Machado Ascendente",
		axe_t20: "Machadinha Celestial",
		axe_t21: "Machado do Vazio",
		// maces
		mace_t1: "Maça de Ferro",
		mace_t2: "Mangual de Cobre",
		mace_t3: "Maça de Bronze",
		mace_t4: "Mangual de Aço",
		mace_t5: "Maça de Guerra",
		mace_t6: "Estrela d'Alva do Soldado",
		mace_t7: "Maça do Cavaleiro",
		mace_t8: "Mangual de Damasco",
		mace_t9: "Maça do Vigia",
		mace_t10: "Estrela d'Alva do Campeão",
		mace_t11: "Maça Templária",
		mace_t12: "Mangual Relíquia",
		mace_t13: "Maça Rúnica",
		mace_t14: "Estrela d'Alva Sagrada",
		mace_t15: "Maça Exaltada",
		mace_t16: "Mangual do Arconte",
		mace_t17: "Maça Soberana",
		mace_t18: "Estrela d'Alva Eterna",
		mace_t19: "Maça Ascendente",
		mace_t20: "Mangual Celestial",
		mace_t21: "Maça do Vazio",
		// greatswords
		greatsword_t1: "Espadagrande de Ferro",
		greatsword_t2: "Claymore de Cobre",
		greatsword_t3: "Zweihänder de Bronze",
		greatsword_t4: "Espadagrande de Aço",
		greatsword_t5: "Claymore de Guerra",
		greatsword_t6: "Espadagrande do Soldado",
		greatsword_t7: "Claymore do Cavaleiro",
		greatsword_t8: "Espadagrande de Damasco",
		greatsword_t9: "Claymore do Vigia",
		greatsword_t10: "Espadagrande do Campeão",
		greatsword_t11: "Zweihänder Templário",
		greatsword_t12: "Espadagrande Relíquia",
		greatsword_t13: "Claymore Rúnica",
		greatsword_t14: "Espadagrande Sagrada",
		greatsword_t15: "Claymore Exaltada",
		greatsword_t16: "Espadagrande do Arconte",
		greatsword_t17: "Zweihänder Soberano",
		greatsword_t18: "Espadagrande Eterna",
		greatsword_t19: "Claymore Ascendente",
		greatsword_t20: "Espadagrande Celestial",
		greatsword_t21: "Espadagrande do Vazio",
		// two-handed-axes
		twoHandedAxe_t1: "Machadão de Ferro",
		twoHandedAxe_t2: "Machado de Batalha de Cobre",
		twoHandedAxe_t3: "Machadão de Bronze",
		twoHandedAxe_t4: "Machado de Batalha de Aço",
		twoHandedAxe_t5: "Machadão de Guerra",
		twoHandedAxe_t6: "Machado de Batalha do Soldado",
		twoHandedAxe_t7: "Machadão do Cavaleiro",
		twoHandedAxe_t8: "Machado de Batalha de Damasco",
		twoHandedAxe_t9: "Machadão do Vigia",
		twoHandedAxe_t10: "Machado de Batalha do Campeão",
		twoHandedAxe_t11: "Machadão Templário",
		twoHandedAxe_t12: "Machado de Batalha Relíquia",
		twoHandedAxe_t13: "Machadão Rúnico",
		twoHandedAxe_t14: "Machado de Batalha Sagrado",
		twoHandedAxe_t15: "Machadão Exaltado",
		twoHandedAxe_t16: "Machado de Batalha do Arconte",
		twoHandedAxe_t17: "Machadão Soberano",
		twoHandedAxe_t18: "Machado de Batalha Eterno",
		twoHandedAxe_t19: "Machadão Ascendente",
		twoHandedAxe_t20: "Machado de Batalha Celestial",
		twoHandedAxe_t21: "Machadão do Vazio",
		// bows
		bow_t1: "Arco de Carvalho",
		bow_t2: "Arco Curto de Freixo",
		bow_t3: "Arco Longo de Olmo",
		bow_t4: "Arco de Teixo",
		bow_t5: "Arco de Guerra de Bordo",
		bow_t6: "Arco de Casca de Ferro",
		bow_t7: "Arco Recurvo",
		bow_t8: "Arco Composto",
		bow_t9: "Arco Longo do Vigia",
		bow_t10: "Arco do Campeão",
		bow_t11: "Arco Templário",
		bow_t12: "Arco de Guerra Relíquia",
		bow_t13: "Arco Longo Rúnico",
		bow_t14: "Arco Sagrado",
		bow_t15: "Arco de Guerra Exaltado",
		bow_t16: "Arco do Arconte",
		bow_t17: "Arco Longo Soberano",
		bow_t18: "Arco Eterno",
		bow_t19: "Arco de Guerra Ascendente",
		bow_t20: "Arco Celestial",
		bow_t21: "Arco do Vazio",
		// wands
		wand_t1: "Varinha do Aprendiz",
		wand_t2: "Varinha do Acólito",
		wand_t3: "Varinha do Erudito",
		wand_t4: "Varinha Mística",
		wand_t5: "Varinha do Invocador",
		wand_t6: "Varinha do Canalizador",
		wand_t7: "Varinha do Conjurador",
		wand_t8: "Varinha do Sábio",
		wand_t9: "Varinha do Vigia",
		wand_t10: "Varinha do Oráculo",
		wand_t11: "Varinha Templária",
		wand_t12: "Varinha Relíquia",
		wand_t13: "Varinha Rúnica",
		wand_t14: "Varinha Sagrada",
		wand_t15: "Varinha Exaltada",
		wand_t16: "Varinha do Arconte",
		wand_t17: "Varinha Soberana",
		wand_t18: "Varinha Eterna",
		wand_t19: "Varinha Ascendente",
		wand_t20: "Varinha Celestial",
		wand_t21: "Varinha do Vazio",
		// staves
		staff_t1: "Cajado do Aprendiz",
		staff_t2: "Cajado do Acólito",
		staff_t3: "Cajado do Erudito",
		staff_t4: "Cajado Místico",
		staff_t5: "Cajado do Invocador",
		staff_t6: "Cajado do Canalizador",
		staff_t7: "Cajado do Conjurador",
		staff_t8: "Cajado do Sábio",
		staff_t9: "Cajado do Vigia",
		staff_t10: "Cajado do Oráculo",
		staff_t11: "Cajado Templário",
		staff_t12: "Cajado Relíquia",
		staff_t13: "Cajado Rúnico",
		staff_t14: "Cajado Sagrado",
		staff_t15: "Cajado Exaltado",
		staff_t16: "Cajado do Arconte",
		staff_t17: "Cajado Soberano",
		staff_t18: "Cajado Eterno",
		staff_t19: "Cajado Ascendente",
		staff_t20: "Cajado Celestial",
		staff_t21: "Cajado do Vazio",
		// helmets
		plate_helmet_t1: "Elmo de Placas de Ferro",
		plate_helmet_t2: "Elmo de Placas de Cobre",
		plate_helmet_t3: "Elmo de Placas de Bronze",
		plate_helmet_t4: "Elmo de Placas de Aço",
		plate_helmet_t5: "Elmo de Placas de Guerra",
		plate_helmet_t6: "Elmo de Placas do Soldado",
		plate_helmet_t7: "Elmo de Placas do Cavaleiro",
		plate_helmet_t8: "Elmo de Placas de Damasco",
		plate_helmet_t9: "Elmo de Placas do Vigia",
		plate_helmet_t10: "Elmo de Placas do Campeão",
		plate_helmet_t11: "Elmo de Placas Templário",
		plate_helmet_t12: "Elmo de Placas Relíquia",
		plate_helmet_t13: "Elmo de Placas Rúnico",
		plate_helmet_t14: "Elmo de Placas Sagrado",
		plate_helmet_t15: "Elmo de Placas Exaltado",
		plate_helmet_t16: "Elmo de Placas do Arconte",
		plate_helmet_t17: "Elmo de Placas Soberano",
		plate_helmet_t18: "Elmo de Placas Eterno",
		plate_helmet_t19: "Elmo de Placas Ascendente",
		plate_helmet_t20: "Elmo de Placas Celestial",
		plate_helmet_t21: "Elmo de Placas Forjado no Vazio",
		leather_helmet_t1: "Capuz de Couro Cru",
		leather_helmet_t2: "Capuz Curtido",
		leather_helmet_t3: "Capuz Curado",
		leather_helmet_t4: "Capuz Cravejado",
		leather_helmet_t5: "Capuz Endurecido",
		leather_helmet_t6: "Capuz do Patrulheiro",
		leather_helmet_t7: "Capuz do Batedor",
		leather_helmet_t8: "Capuz Tratado",
		leather_helmet_t9: "Capuz do Vigia",
		leather_helmet_t10: "Capuz do Campeão",
		leather_helmet_t11: "Capuz Templário",
		leather_helmet_t12: "Capuz Relíquia",
		leather_helmet_t13: "Capuz Rúnico",
		leather_helmet_t14: "Capuz Sagrado",
		leather_helmet_t15: "Capuz Exaltado",
		leather_helmet_t16: "Capuz do Arconte",
		leather_helmet_t17: "Capuz Soberano",
		leather_helmet_t18: "Capuz Eterno",
		leather_helmet_t19: "Capuz Ascendente",
		leather_helmet_t20: "Capuz Celestial",
		leather_helmet_t21: "Capuz de Couro do Vazio",
		silk_helmet_t1: "Capuz de Linho",
		silk_helmet_t2: "Capuz de Algodão",
		silk_helmet_t3: "Capuz Tecido",
		silk_helmet_t4: "Capuz Fino",
		silk_helmet_t5: "Capuz Encantado",
		silk_helmet_t6: "Capuz Místico",
		silk_helmet_t7: "Capuz Arcano",
		silk_helmet_t8: "Capuz do Sábio",
		silk_helmet_t9: "Capuz do Vigia",
		silk_helmet_t10: "Capuz do Oráculo",
		silk_helmet_t11: "Capuz Templário",
		silk_helmet_t12: "Capuz Relíquia",
		silk_helmet_t13: "Capuz Rúnico",
		silk_helmet_t14: "Capuz Sagrado",
		silk_helmet_t15: "Capuz Exaltado",
		silk_helmet_t16: "Capuz do Arconte",
		silk_helmet_t17: "Capuz Soberano",
		silk_helmet_t18: "Capuz Eterno",
		silk_helmet_t19: "Capuz Ascendente",
		silk_helmet_t20: "Capuz Celestial",
		silk_helmet_t21: "Capuz de Seda Tecido no Vazio",
		// chestplates
		plate_chestplate_t1: "Peitoral de Placas de Ferro",
		plate_chestplate_t2: "Peitoral de Placas de Cobre",
		plate_chestplate_t3: "Peitoral de Placas de Bronze",
		plate_chestplate_t4: "Peitoral de Placas de Aço",
		plate_chestplate_t5: "Peitoral de Placas de Guerra",
		plate_chestplate_t6: "Peitoral de Placas do Soldado",
		plate_chestplate_t7: "Peitoral de Placas do Cavaleiro",
		plate_chestplate_t8: "Peitoral de Placas de Damasco",
		plate_chestplate_t9: "Peitoral de Placas do Vigia",
		plate_chestplate_t10: "Peitoral de Placas do Campeão",
		plate_chestplate_t11: "Peitoral de Placas Templário",
		plate_chestplate_t12: "Peitoral de Placas Relíquia",
		plate_chestplate_t13: "Peitoral de Placas Rúnico",
		plate_chestplate_t14: "Peitoral de Placas Sagrado",
		plate_chestplate_t15: "Peitoral de Placas Exaltado",
		plate_chestplate_t16: "Peitoral de Placas do Arconte",
		plate_chestplate_t17: "Peitoral de Placas Soberano",
		plate_chestplate_t18: "Peitoral de Placas Eterno",
		plate_chestplate_t19: "Peitoral de Placas Ascendente",
		plate_chestplate_t20: "Peitoral de Placas Celestial",
		plate_chestplate_t21: "Peitoral de Placas Forjado no Vazio",
		leather_chestplate_t1: "Colete de Couro Cru",
		leather_chestplate_t2: "Colete Curtido",
		leather_chestplate_t3: "Colete Curado",
		leather_chestplate_t4: "Colete Cravejado",
		leather_chestplate_t5: "Colete Endurecido",
		leather_chestplate_t6: "Colete do Patrulheiro",
		leather_chestplate_t7: "Colete do Batedor",
		leather_chestplate_t8: "Colete Tratado",
		leather_chestplate_t9: "Colete do Vigia",
		leather_chestplate_t10: "Colete do Campeão",
		leather_chestplate_t11: "Colete Templário",
		leather_chestplate_t12: "Colete Relíquia",
		leather_chestplate_t13: "Colete Rúnico",
		leather_chestplate_t14: "Colete Sagrado",
		leather_chestplate_t15: "Colete Exaltado",
		leather_chestplate_t16: "Colete do Arconte",
		leather_chestplate_t17: "Colete Soberano",
		leather_chestplate_t18: "Colete Eterno",
		leather_chestplate_t19: "Colete Ascendente",
		leather_chestplate_t20: "Colete Celestial",
		leather_chestplate_t21: "Colete de Couro do Vazio",
		silk_chestplate_t1: "Túnica de Linho",
		silk_chestplate_t2: "Túnica de Algodão",
		silk_chestplate_t3: "Túnica Tecida",
		silk_chestplate_t4: "Túnica Fina",
		silk_chestplate_t5: "Túnica Encantada",
		silk_chestplate_t6: "Túnica Mística",
		silk_chestplate_t7: "Túnica Arcana",
		silk_chestplate_t8: "Túnica do Sábio",
		silk_chestplate_t9: "Túnica do Vigia",
		silk_chestplate_t10: "Túnica do Oráculo",
		silk_chestplate_t11: "Túnica Templária",
		silk_chestplate_t12: "Túnica Relíquia",
		silk_chestplate_t13: "Túnica Rúnica",
		silk_chestplate_t14: "Túnica Sagrada",
		silk_chestplate_t15: "Túnica Exaltada",
		silk_chestplate_t16: "Túnica do Arconte",
		silk_chestplate_t17: "Túnica Soberana",
		silk_chestplate_t18: "Túnica Eterna",
		silk_chestplate_t19: "Túnica Ascendente",
		silk_chestplate_t20: "Túnica Celestial",
		silk_chestplate_t21: "Túnica de Seda Tecido no Vazio",
		// boots
		plate_boots_t1: "Botas de Placas de Ferro",
		plate_boots_t2: "Botas de Placas de Cobre",
		plate_boots_t3: "Botas de Placas de Bronze",
		plate_boots_t4: "Botas de Placas de Aço",
		plate_boots_t5: "Botas de Placas de Guerra",
		plate_boots_t6: "Botas de Placas do Soldado",
		plate_boots_t7: "Botas de Placas do Cavaleiro",
		plate_boots_t8: "Botas de Placas de Damasco",
		plate_boots_t9: "Botas de Placas do Vigia",
		plate_boots_t10: "Botas de Placas do Campeão",
		plate_boots_t11: "Botas de Placas Templária",
		plate_boots_t12: "Botas de Placas Relíquia",
		plate_boots_t13: "Botas de Placas Rúnica",
		plate_boots_t14: "Botas de Placas Sagrada",
		plate_boots_t15: "Botas de Placas Exaltada",
		plate_boots_t16: "Botas de Placas do Arconte",
		plate_boots_t17: "Botas de Placas Soberana",
		plate_boots_t18: "Botas de Placas Eterna",
		plate_boots_t19: "Botas de Placas Ascendente",
		plate_boots_t20: "Botas de Placas Celestial",
		plate_boots_t21: "Botas de Placas Forjado no Vazio",
		leather_boots_t1: "Botas de Couro Cru",
		leather_boots_t2: "Botas Curtida",
		leather_boots_t3: "Botas Curada",
		leather_boots_t4: "Botas Cravejada",
		leather_boots_t5: "Botas Endurecida",
		leather_boots_t6: "Botas do Patrulheiro",
		leather_boots_t7: "Botas do Batedor",
		leather_boots_t8: "Botas Tratada",
		leather_boots_t9: "Botas do Vigia",
		leather_boots_t10: "Botas do Campeão",
		leather_boots_t11: "Botas Templária",
		leather_boots_t12: "Botas Relíquia",
		leather_boots_t13: "Botas Rúnica",
		leather_boots_t14: "Botas Sagrada",
		leather_boots_t15: "Botas Exaltada",
		leather_boots_t16: "Botas do Arconte",
		leather_boots_t17: "Botas Soberana",
		leather_boots_t18: "Botas Eterna",
		leather_boots_t19: "Botas Ascendente",
		leather_boots_t20: "Botas Celestial",
		leather_boots_t21: "Botas de Couro do Vazio",
		silk_boots_t1: "Sapatilhas de Linho",
		silk_boots_t2: "Sapatilhas de Algodão",
		silk_boots_t3: "Sapatilhas Tecida",
		silk_boots_t4: "Sapatilhas Fina",
		silk_boots_t5: "Sapatilhas Encantada",
		silk_boots_t6: "Sapatilhas Mística",
		silk_boots_t7: "Sapatilhas Arcana",
		silk_boots_t8: "Sapatilhas do Sábio",
		silk_boots_t9: "Sapatilhas do Vigia",
		silk_boots_t10: "Sapatilhas do Oráculo",
		silk_boots_t11: "Sapatilhas Templária",
		silk_boots_t12: "Sapatilhas Relíquia",
		silk_boots_t13: "Sapatilhas Rúnica",
		silk_boots_t14: "Sapatilhas Sagrada",
		silk_boots_t15: "Sapatilhas Exaltada",
		silk_boots_t16: "Sapatilhas do Arconte",
		silk_boots_t17: "Sapatilhas Soberana",
		silk_boots_t18: "Sapatilhas Eterna",
		silk_boots_t19: "Sapatilhas Ascendente",
		silk_boots_t20: "Sapatilhas Celestial",
		silk_boots_t21: "Sapatilhas de Seda Tecido no Vazio",
		// gloves
		plate_gloves_t1: "Manoplas de Ferro",
		plate_gloves_t2: "Manoplas de Cobre",
		plate_gloves_t3: "Manoplas de Bronze",
		plate_gloves_t4: "Manoplas de Aço",
		plate_gloves_t5: "Manoplas de Guerra",
		plate_gloves_t6: "Manoplas do Soldado",
		plate_gloves_t7: "Manoplas do Cavaleiro",
		plate_gloves_t8: "Manoplas de Damasco",
		plate_gloves_t9: "Manoplas do Vigia",
		plate_gloves_t10: "Manoplas do Campeão",
		plate_gloves_t11: "Manoplas Templária",
		plate_gloves_t12: "Manoplas Relíquia",
		plate_gloves_t13: "Manoplas Rúnica",
		plate_gloves_t14: "Manoplas Sagrada",
		plate_gloves_t15: "Manoplas Exaltada",
		plate_gloves_t16: "Manoplas do Arconte",
		plate_gloves_t17: "Manoplas Soberana",
		plate_gloves_t18: "Manoplas Eterna",
		plate_gloves_t19: "Manoplas Ascendente",
		plate_gloves_t20: "Manoplas Celestial",
		plate_gloves_t21: "Manoplas Forjado no Vazio",
		leather_gloves_t1: "Luvas de Couro Cru",
		leather_gloves_t2: "Luvas Curtida",
		leather_gloves_t3: "Luvas Curada",
		leather_gloves_t4: "Luvas Cravejada",
		leather_gloves_t5: "Luvas Endurecida",
		leather_gloves_t6: "Luvas do Patrulheiro",
		leather_gloves_t7: "Luvas do Batedor",
		leather_gloves_t8: "Luvas Tratada",
		leather_gloves_t9: "Luvas do Vigia",
		leather_gloves_t10: "Luvas do Campeão",
		leather_gloves_t11: "Luvas Templária",
		leather_gloves_t12: "Luvas Relíquia",
		leather_gloves_t13: "Luvas Rúnica",
		leather_gloves_t14: "Luvas Sagrada",
		leather_gloves_t15: "Luvas Exaltada",
		leather_gloves_t16: "Luvas do Arconte",
		leather_gloves_t17: "Luvas Soberana",
		leather_gloves_t18: "Luvas Eterna",
		leather_gloves_t19: "Luvas Ascendente",
		leather_gloves_t20: "Luvas Celestial",
		leather_gloves_t21: "Luvas de Couro do Vazio",
		silk_gloves_t1: "Bandagens de Linho",
		silk_gloves_t2: "Bandagens de Algodão",
		silk_gloves_t3: "Bandagens Tecida",
		silk_gloves_t4: "Bandagens Fina",
		silk_gloves_t5: "Bandagens Encantada",
		silk_gloves_t6: "Bandagens Mística",
		silk_gloves_t7: "Bandagens Arcana",
		silk_gloves_t8: "Bandagens do Sábio",
		silk_gloves_t9: "Bandagens do Vigia",
		silk_gloves_t10: "Bandagens do Oráculo",
		silk_gloves_t11: "Bandagens Templária",
		silk_gloves_t12: "Bandagens Relíquia",
		silk_gloves_t13: "Bandagens Rúnica",
		silk_gloves_t14: "Bandagens Sagrada",
		silk_gloves_t15: "Bandagens Exaltada",
		silk_gloves_t16: "Bandagens do Arconte",
		silk_gloves_t17: "Bandagens Soberana",
		silk_gloves_t18: "Bandagens Eterna",
		silk_gloves_t19: "Bandagens Ascendente",
		silk_gloves_t20: "Bandagens Celestial",
		silk_gloves_t21: "Bandagens de Seda Tecido no Vazio",
		// shields
		plate_shield_t1: "Escudo de Torre de Ferro",
		plate_shield_t2: "Escudo de Torre de Cobre",
		plate_shield_t3: "Escudo de Torre de Bronze",
		plate_shield_t4: "Escudo de Torre de Aço",
		plate_shield_t5: "Escudo de Torre de Guerra",
		plate_shield_t6: "Escudo de Torre do Soldado",
		plate_shield_t7: "Escudo de Torre do Cavaleiro",
		plate_shield_t8: "Escudo de Torre de Damasco",
		plate_shield_t9: "Escudo de Torre do Vigia",
		plate_shield_t10: "Escudo de Torre do Campeão",
		plate_shield_t11: "Escudo de Torre Templário",
		plate_shield_t12: "Escudo de Torre Relíquia",
		plate_shield_t13: "Escudo de Torre Rúnico",
		plate_shield_t14: "Escudo de Torre Sagrado",
		plate_shield_t15: "Escudo de Torre Exaltado",
		plate_shield_t16: "Escudo de Torre do Arconte",
		plate_shield_t17: "Escudo de Torre Soberano",
		plate_shield_t18: "Escudo de Torre Eterno",
		plate_shield_t19: "Escudo de Torre Ascendente",
		plate_shield_t20: "Escudo de Torre Celestial",
		plate_shield_t21: "Escudo de Torre Forjado no Vazio",
		leather_shield_t1: "Brocal de Couro Cru",
		leather_shield_t2: "Brocal Curtido",
		leather_shield_t3: "Brocal Curado",
		leather_shield_t4: "Brocal Cravejado",
		leather_shield_t5: "Brocal Endurecido",
		leather_shield_t6: "Brocal do Patrulheiro",
		leather_shield_t7: "Brocal do Batedor",
		leather_shield_t8: "Brocal Tratado",
		leather_shield_t9: "Brocal do Vigia",
		leather_shield_t10: "Brocal do Campeão",
		leather_shield_t11: "Brocal Templário",
		leather_shield_t12: "Brocal Relíquia",
		leather_shield_t13: "Brocal Rúnico",
		leather_shield_t14: "Brocal Sagrado",
		leather_shield_t15: "Brocal Exaltado",
		leather_shield_t16: "Brocal do Arconte",
		leather_shield_t17: "Brocal Soberano",
		leather_shield_t18: "Brocal Eterno",
		leather_shield_t19: "Brocal Ascendente",
		leather_shield_t20: "Brocal Celestial",
		leather_shield_t21: "Brocal do Vazio",
		silk_shield_t1: "Égide de Linho",
		silk_shield_t2: "Égide de Algodão",
		silk_shield_t3: "Égide Tecida",
		silk_shield_t4: "Égide Fina",
		silk_shield_t5: "Égide Encantada",
		silk_shield_t6: "Égide Mística",
		silk_shield_t7: "Égide Arcana",
		silk_shield_t8: "Égide do Sábio",
		silk_shield_t9: "Égide do Oráculo",
		silk_shield_t10: "Égide do Vidente",
		silk_shield_t11: "Égide Templária",
		silk_shield_t12: "Égide Relíquia",
		silk_shield_t13: "Égide Rúnica",
		silk_shield_t14: "Égide Sagrada",
		silk_shield_t15: "Égide Exaltada",
		silk_shield_t16: "Égide do Arconte",
		silk_shield_t17: "Égide Soberana",
		silk_shield_t18: "Égide Eterna",
		silk_shield_t19: "Égide Ascendente",
		silk_shield_t20: "Égide Celestial",
		silk_shield_t21: "Égide Tecido no Vazio",
		// tomes
		tome_t1: "Tomo do Aprendiz",
		tome_t2: "Tomo do Acólito",
		tome_t3: "Tomo do Iniciado",
		tome_t4: "Tomo do Erudito",
		tome_t5: "Tomo do Adepto",
		tome_t6: "Tomo do Magíster",
		tome_t7: "Tomo Místico",
		tome_t8: "Tomo Arcano",
		tome_t9: "Tomo do Sábio",
		tome_t10: "Tomo do Oráculo",
		tome_t11: "Tomo do Hierofante",
		tome_t12: "Tomo Templário",
		tome_t13: "Tomo Rúnico",
		tome_t14: "Tomo Sagrado",
		tome_t15: "Tomo Exaltado",
		tome_t16: "Tomo do Arconte",
		tome_t17: "Tomo Soberano",
		tome_t18: "Tomo Eterno",
		tome_t19: "Tomo Ascendente",
		tome_t20: "Tomo Celestial",
		tome_t21: "Tomo Inscrito no Vazio",
		// quivers
		quiver_t1: "Aljava de Couro",
		quiver_t2: "Aljava Curtida",
		quiver_t3: "Aljava do Caçador",
		quiver_t4: "Aljava do Patrulheiro",
		quiver_t5: "Aljava do Escaramuçador",
		quiver_t6: "Aljava do Batedor",
		quiver_t7: "Aljava do Atirador",
		quiver_t8: "Aljava Tratada",
		quiver_t9: "Aljava do Vigia",
		quiver_t10: "Aljava do Campeão",
		quiver_t11: "Aljava Templária",
		quiver_t12: "Aljava Relíquia",
		quiver_t13: "Aljava Rúnica",
		quiver_t14: "Aljava Sagrada",
		quiver_t15: "Aljava Exaltada",
		quiver_t16: "Aljava do Arconte",
		quiver_t17: "Aljava Soberana",
		quiver_t18: "Aljava Eterna",
		quiver_t19: "Aljava Ascendente",
		quiver_t20: "Aljava Celestial",
		quiver_t21: "Aljava do Vazio",
		// rings
		cobalt_ring: "Anel de Cobalto",
		garnet_ring: "Anel de Granada",
		topaz_ring: "Anel de Topázio",
		obsidian_ring: "Anel de Obsidiana",
		coral_ring: "Anel de Coral",
		lapis_ring: "Anel de Lápis",
		// amulets
		gold_amulet: "Amuleto Prismático",
		jade_amulet: "Amuleto de Jade",
		amber_amulet: "Amuleto de Âmbar",
		lapis_amulet: "Amuleto de Lápis",
		// belts
		leather_belt: "Cinto de Couro",
		chain_belt: "Cinto de Correntes",
		studded_belt: "Cinto Cravejado",
		cloth_belt: "Cinto de Pano",
		prismatic_belt: "Cinto Prismático",
		silk_belt: "Cinto de Seda",
	},
	templateGender: {
		// swords
		sword_t1: "f",
		sword_t2: "f",
		sword_t3: "m",
		sword_t4: "f",
		sword_t5: "f",
		sword_t6: "m",
		sword_t7: "f",
		sword_t8: "f",
		sword_t9: "f",
		sword_t10: "m",
		sword_t11: "f",
		sword_t12: "f",
		sword_t13: "m",
		sword_t14: "f",
		sword_t15: "m",
		sword_t16: "f",
		sword_t17: "f",
		sword_t18: "m",
		sword_t19: "f",
		sword_t20: "m",
		sword_t21: "m",
		// daggers
		dagger_t1: "f",
		dagger_t2: "m",
		dagger_t3: "m",
		dagger_t4: "f",
		dagger_t5: "f",
		dagger_t6: "f",
		dagger_t7: "m",
		dagger_t8: "f",
		dagger_t9: "m",
		dagger_t10: "f",
		dagger_t11: "f",
		dagger_t12: "m",
		dagger_t13: "m",
		dagger_t14: "f",
		dagger_t15: "f",
		dagger_t16: "m",
		dagger_t17: "f",
		dagger_t18: "m",
		dagger_t19: "f",
		dagger_t20: "f",
		dagger_t21: "f",
		// axes
		axe_t1: "m",
		axe_t2: "f",
		axe_t3: "m",
		axe_t4: "f",
		axe_t5: "m",
		axe_t6: "m",
		axe_t7: "m",
		axe_t8: "f",
		axe_t9: "m",
		axe_t10: "m",
		axe_t11: "m",
		axe_t12: "f",
		axe_t13: "m",
		axe_t14: "m",
		axe_t15: "m",
		axe_t16: "f",
		axe_t17: "m",
		axe_t18: "m",
		axe_t19: "m",
		axe_t20: "f",
		axe_t21: "m",
		// maces
		mace_t1: "f",
		mace_t2: "m",
		mace_t3: "f",
		mace_t4: "m",
		mace_t5: "f",
		mace_t6: "f",
		mace_t7: "f",
		mace_t8: "m",
		mace_t9: "f",
		mace_t10: "f",
		mace_t11: "f",
		mace_t12: "m",
		mace_t13: "f",
		mace_t14: "f",
		mace_t15: "f",
		mace_t16: "m",
		mace_t17: "f",
		mace_t18: "f",
		mace_t19: "f",
		mace_t20: "m",
		mace_t21: "f",
		// greatswords
		greatsword_t1: "f",
		greatsword_t2: "f",
		greatsword_t3: "m",
		greatsword_t4: "f",
		greatsword_t5: "f",
		greatsword_t6: "f",
		greatsword_t7: "f",
		greatsword_t8: "f",
		greatsword_t9: "f",
		greatsword_t10: "f",
		greatsword_t11: "m",
		greatsword_t12: "f",
		greatsword_t13: "f",
		greatsword_t14: "f",
		greatsword_t15: "f",
		greatsword_t16: "f",
		greatsword_t17: "m",
		greatsword_t18: "f",
		greatsword_t19: "f",
		greatsword_t20: "f",
		greatsword_t21: "f",
		// two-handed-axes
		twoHandedAxe_t1: "m",
		twoHandedAxe_t2: "m",
		twoHandedAxe_t3: "m",
		twoHandedAxe_t4: "m",
		twoHandedAxe_t5: "m",
		twoHandedAxe_t6: "m",
		twoHandedAxe_t7: "m",
		twoHandedAxe_t8: "m",
		twoHandedAxe_t9: "m",
		twoHandedAxe_t10: "m",
		twoHandedAxe_t11: "m",
		twoHandedAxe_t12: "m",
		twoHandedAxe_t13: "m",
		twoHandedAxe_t14: "m",
		twoHandedAxe_t15: "m",
		twoHandedAxe_t16: "m",
		twoHandedAxe_t17: "m",
		twoHandedAxe_t18: "m",
		twoHandedAxe_t19: "m",
		twoHandedAxe_t20: "m",
		twoHandedAxe_t21: "m",
		// bows
		bow_t1: "m",
		bow_t2: "m",
		bow_t3: "m",
		bow_t4: "m",
		bow_t5: "m",
		bow_t6: "m",
		bow_t7: "m",
		bow_t8: "m",
		bow_t9: "m",
		bow_t10: "m",
		bow_t11: "m",
		bow_t12: "m",
		bow_t13: "m",
		bow_t14: "m",
		bow_t15: "m",
		bow_t16: "m",
		bow_t17: "m",
		bow_t18: "m",
		bow_t19: "m",
		bow_t20: "m",
		bow_t21: "m",
		// wands
		wand_t1: "f",
		wand_t2: "f",
		wand_t3: "f",
		wand_t4: "f",
		wand_t5: "f",
		wand_t6: "f",
		wand_t7: "f",
		wand_t8: "f",
		wand_t9: "f",
		wand_t10: "f",
		wand_t11: "f",
		wand_t12: "f",
		wand_t13: "f",
		wand_t14: "f",
		wand_t15: "f",
		wand_t16: "f",
		wand_t17: "f",
		wand_t18: "f",
		wand_t19: "f",
		wand_t20: "f",
		wand_t21: "f",
		// staves
		staff_t1: "m",
		staff_t2: "m",
		staff_t3: "m",
		staff_t4: "m",
		staff_t5: "m",
		staff_t6: "m",
		staff_t7: "m",
		staff_t8: "m",
		staff_t9: "m",
		staff_t10: "m",
		staff_t11: "m",
		staff_t12: "m",
		staff_t13: "m",
		staff_t14: "m",
		staff_t15: "m",
		staff_t16: "m",
		staff_t17: "m",
		staff_t18: "m",
		staff_t19: "m",
		staff_t20: "m",
		staff_t21: "m",
		// helmets
		plate_helmet_t1: "m",
		plate_helmet_t2: "m",
		plate_helmet_t3: "m",
		plate_helmet_t4: "m",
		plate_helmet_t5: "m",
		plate_helmet_t6: "m",
		plate_helmet_t7: "m",
		plate_helmet_t8: "m",
		plate_helmet_t9: "m",
		plate_helmet_t10: "m",
		plate_helmet_t11: "m",
		plate_helmet_t12: "m",
		plate_helmet_t13: "m",
		plate_helmet_t14: "m",
		plate_helmet_t15: "m",
		plate_helmet_t16: "m",
		plate_helmet_t17: "m",
		plate_helmet_t18: "m",
		plate_helmet_t19: "m",
		plate_helmet_t20: "m",
		plate_helmet_t21: "m",
		leather_helmet_t1: "m",
		leather_helmet_t2: "m",
		leather_helmet_t3: "m",
		leather_helmet_t4: "m",
		leather_helmet_t5: "m",
		leather_helmet_t6: "m",
		leather_helmet_t7: "m",
		leather_helmet_t8: "m",
		leather_helmet_t9: "m",
		leather_helmet_t10: "m",
		leather_helmet_t11: "m",
		leather_helmet_t12: "m",
		leather_helmet_t13: "m",
		leather_helmet_t14: "m",
		leather_helmet_t15: "m",
		leather_helmet_t16: "m",
		leather_helmet_t17: "m",
		leather_helmet_t18: "m",
		leather_helmet_t19: "m",
		leather_helmet_t20: "m",
		leather_helmet_t21: "m",
		silk_helmet_t1: "m",
		silk_helmet_t2: "m",
		silk_helmet_t3: "m",
		silk_helmet_t4: "m",
		silk_helmet_t5: "m",
		silk_helmet_t6: "m",
		silk_helmet_t7: "m",
		silk_helmet_t8: "m",
		silk_helmet_t9: "m",
		silk_helmet_t10: "m",
		silk_helmet_t11: "m",
		silk_helmet_t12: "m",
		silk_helmet_t13: "m",
		silk_helmet_t14: "m",
		silk_helmet_t15: "m",
		silk_helmet_t16: "m",
		silk_helmet_t17: "m",
		silk_helmet_t18: "m",
		silk_helmet_t19: "m",
		silk_helmet_t20: "m",
		silk_helmet_t21: "m",
		// chestplates
		plate_chestplate_t1: "m",
		plate_chestplate_t2: "m",
		plate_chestplate_t3: "m",
		plate_chestplate_t4: "m",
		plate_chestplate_t5: "m",
		plate_chestplate_t6: "m",
		plate_chestplate_t7: "m",
		plate_chestplate_t8: "m",
		plate_chestplate_t9: "m",
		plate_chestplate_t10: "m",
		plate_chestplate_t11: "m",
		plate_chestplate_t12: "m",
		plate_chestplate_t13: "m",
		plate_chestplate_t14: "m",
		plate_chestplate_t15: "m",
		plate_chestplate_t16: "m",
		plate_chestplate_t17: "m",
		plate_chestplate_t18: "m",
		plate_chestplate_t19: "m",
		plate_chestplate_t20: "m",
		plate_chestplate_t21: "m",
		leather_chestplate_t1: "m",
		leather_chestplate_t2: "m",
		leather_chestplate_t3: "m",
		leather_chestplate_t4: "m",
		leather_chestplate_t5: "m",
		leather_chestplate_t6: "m",
		leather_chestplate_t7: "m",
		leather_chestplate_t8: "m",
		leather_chestplate_t9: "m",
		leather_chestplate_t10: "m",
		leather_chestplate_t11: "m",
		leather_chestplate_t12: "m",
		leather_chestplate_t13: "m",
		leather_chestplate_t14: "m",
		leather_chestplate_t15: "m",
		leather_chestplate_t16: "m",
		leather_chestplate_t17: "m",
		leather_chestplate_t18: "m",
		leather_chestplate_t19: "m",
		leather_chestplate_t20: "m",
		leather_chestplate_t21: "m",
		silk_chestplate_t1: "f",
		silk_chestplate_t2: "f",
		silk_chestplate_t3: "f",
		silk_chestplate_t4: "f",
		silk_chestplate_t5: "f",
		silk_chestplate_t6: "f",
		silk_chestplate_t7: "f",
		silk_chestplate_t8: "f",
		silk_chestplate_t9: "f",
		silk_chestplate_t10: "f",
		silk_chestplate_t11: "f",
		silk_chestplate_t12: "f",
		silk_chestplate_t13: "f",
		silk_chestplate_t14: "f",
		silk_chestplate_t15: "f",
		silk_chestplate_t16: "f",
		silk_chestplate_t17: "f",
		silk_chestplate_t18: "f",
		silk_chestplate_t19: "f",
		silk_chestplate_t20: "f",
		silk_chestplate_t21: "f",
		// boots
		plate_boots_t1: "f",
		plate_boots_t2: "f",
		plate_boots_t3: "f",
		plate_boots_t4: "f",
		plate_boots_t5: "f",
		plate_boots_t6: "f",
		plate_boots_t7: "f",
		plate_boots_t8: "f",
		plate_boots_t9: "f",
		plate_boots_t10: "f",
		plate_boots_t11: "f",
		plate_boots_t12: "f",
		plate_boots_t13: "f",
		plate_boots_t14: "f",
		plate_boots_t15: "f",
		plate_boots_t16: "f",
		plate_boots_t17: "f",
		plate_boots_t18: "f",
		plate_boots_t19: "f",
		plate_boots_t20: "f",
		plate_boots_t21: "f",
		leather_boots_t1: "f",
		leather_boots_t2: "f",
		leather_boots_t3: "f",
		leather_boots_t4: "f",
		leather_boots_t5: "f",
		leather_boots_t6: "f",
		leather_boots_t7: "f",
		leather_boots_t8: "f",
		leather_boots_t9: "f",
		leather_boots_t10: "f",
		leather_boots_t11: "f",
		leather_boots_t12: "f",
		leather_boots_t13: "f",
		leather_boots_t14: "f",
		leather_boots_t15: "f",
		leather_boots_t16: "f",
		leather_boots_t17: "f",
		leather_boots_t18: "f",
		leather_boots_t19: "f",
		leather_boots_t20: "f",
		leather_boots_t21: "f",
		silk_boots_t1: "f",
		silk_boots_t2: "f",
		silk_boots_t3: "f",
		silk_boots_t4: "f",
		silk_boots_t5: "f",
		silk_boots_t6: "f",
		silk_boots_t7: "f",
		silk_boots_t8: "f",
		silk_boots_t9: "f",
		silk_boots_t10: "f",
		silk_boots_t11: "f",
		silk_boots_t12: "f",
		silk_boots_t13: "f",
		silk_boots_t14: "f",
		silk_boots_t15: "f",
		silk_boots_t16: "f",
		silk_boots_t17: "f",
		silk_boots_t18: "f",
		silk_boots_t19: "f",
		silk_boots_t20: "f",
		silk_boots_t21: "f",
		// gloves
		plate_gloves_t1: "f",
		plate_gloves_t2: "f",
		plate_gloves_t3: "f",
		plate_gloves_t4: "f",
		plate_gloves_t5: "f",
		plate_gloves_t6: "f",
		plate_gloves_t7: "f",
		plate_gloves_t8: "f",
		plate_gloves_t9: "f",
		plate_gloves_t10: "f",
		plate_gloves_t11: "f",
		plate_gloves_t12: "f",
		plate_gloves_t13: "f",
		plate_gloves_t14: "f",
		plate_gloves_t15: "f",
		plate_gloves_t16: "f",
		plate_gloves_t17: "f",
		plate_gloves_t18: "f",
		plate_gloves_t19: "f",
		plate_gloves_t20: "f",
		plate_gloves_t21: "f",
		leather_gloves_t1: "f",
		leather_gloves_t2: "f",
		leather_gloves_t3: "f",
		leather_gloves_t4: "f",
		leather_gloves_t5: "f",
		leather_gloves_t6: "f",
		leather_gloves_t7: "f",
		leather_gloves_t8: "f",
		leather_gloves_t9: "f",
		leather_gloves_t10: "f",
		leather_gloves_t11: "f",
		leather_gloves_t12: "f",
		leather_gloves_t13: "f",
		leather_gloves_t14: "f",
		leather_gloves_t15: "f",
		leather_gloves_t16: "f",
		leather_gloves_t17: "f",
		leather_gloves_t18: "f",
		leather_gloves_t19: "f",
		leather_gloves_t20: "f",
		leather_gloves_t21: "f",
		silk_gloves_t1: "f",
		silk_gloves_t2: "f",
		silk_gloves_t3: "f",
		silk_gloves_t4: "f",
		silk_gloves_t5: "f",
		silk_gloves_t6: "f",
		silk_gloves_t7: "f",
		silk_gloves_t8: "f",
		silk_gloves_t9: "f",
		silk_gloves_t10: "f",
		silk_gloves_t11: "f",
		silk_gloves_t12: "f",
		silk_gloves_t13: "f",
		silk_gloves_t14: "f",
		silk_gloves_t15: "f",
		silk_gloves_t16: "f",
		silk_gloves_t17: "f",
		silk_gloves_t18: "f",
		silk_gloves_t19: "f",
		silk_gloves_t20: "f",
		silk_gloves_t21: "f",
		// shields
		plate_shield_t1: "m",
		plate_shield_t2: "m",
		plate_shield_t3: "m",
		plate_shield_t4: "m",
		plate_shield_t5: "m",
		plate_shield_t6: "m",
		plate_shield_t7: "m",
		plate_shield_t8: "m",
		plate_shield_t9: "m",
		plate_shield_t10: "m",
		plate_shield_t11: "m",
		plate_shield_t12: "m",
		plate_shield_t13: "m",
		plate_shield_t14: "m",
		plate_shield_t15: "m",
		plate_shield_t16: "m",
		plate_shield_t17: "m",
		plate_shield_t18: "m",
		plate_shield_t19: "m",
		plate_shield_t20: "m",
		plate_shield_t21: "m",
		leather_shield_t1: "m",
		leather_shield_t2: "m",
		leather_shield_t3: "m",
		leather_shield_t4: "m",
		leather_shield_t5: "m",
		leather_shield_t6: "m",
		leather_shield_t7: "m",
		leather_shield_t8: "m",
		leather_shield_t9: "m",
		leather_shield_t10: "m",
		leather_shield_t11: "m",
		leather_shield_t12: "m",
		leather_shield_t13: "m",
		leather_shield_t14: "m",
		leather_shield_t15: "m",
		leather_shield_t16: "m",
		leather_shield_t17: "m",
		leather_shield_t18: "m",
		leather_shield_t19: "m",
		leather_shield_t20: "m",
		leather_shield_t21: "m",
		silk_shield_t1: "f",
		silk_shield_t2: "f",
		silk_shield_t3: "f",
		silk_shield_t4: "f",
		silk_shield_t5: "f",
		silk_shield_t6: "f",
		silk_shield_t7: "f",
		silk_shield_t8: "f",
		silk_shield_t9: "f",
		silk_shield_t10: "f",
		silk_shield_t11: "f",
		silk_shield_t12: "f",
		silk_shield_t13: "f",
		silk_shield_t14: "f",
		silk_shield_t15: "f",
		silk_shield_t16: "f",
		silk_shield_t17: "f",
		silk_shield_t18: "f",
		silk_shield_t19: "f",
		silk_shield_t20: "f",
		silk_shield_t21: "f",
		// tomes
		tome_t1: "m",
		tome_t2: "m",
		tome_t3: "m",
		tome_t4: "m",
		tome_t5: "m",
		tome_t6: "m",
		tome_t7: "m",
		tome_t8: "m",
		tome_t9: "m",
		tome_t10: "m",
		tome_t11: "m",
		tome_t12: "m",
		tome_t13: "m",
		tome_t14: "m",
		tome_t15: "m",
		tome_t16: "m",
		tome_t17: "m",
		tome_t18: "m",
		tome_t19: "m",
		tome_t20: "m",
		tome_t21: "m",
		// quivers
		quiver_t1: "f",
		quiver_t2: "f",
		quiver_t3: "f",
		quiver_t4: "f",
		quiver_t5: "f",
		quiver_t6: "f",
		quiver_t7: "f",
		quiver_t8: "f",
		quiver_t9: "f",
		quiver_t10: "f",
		quiver_t11: "f",
		quiver_t12: "f",
		quiver_t13: "f",
		quiver_t14: "f",
		quiver_t15: "f",
		quiver_t16: "f",
		quiver_t17: "f",
		quiver_t18: "f",
		quiver_t19: "f",
		quiver_t20: "f",
		quiver_t21: "f",
		// rings
		cobalt_ring: "m",
		garnet_ring: "m",
		topaz_ring: "m",
		obsidian_ring: "m",
		coral_ring: "m",
		lapis_ring: "m",
		// amulets
		gold_amulet: "m",
		jade_amulet: "m",
		amber_amulet: "m",
		lapis_amulet: "m",
		// belts
		leather_belt: "m",
		chain_belt: "m",
		studded_belt: "m",
		cloth_belt: "m",
		prismatic_belt: "m",
		silk_belt: "m",
	},
	prefixForms: {
		localDefenseFlat: { m: "Reforçado", f: "Reforçada" },
		armorFlat: { m: "Robusto", f: "Robusta" },
		evasionFlat: { m: "Ágil", f: "Ágil" },
		barrierFlat: { m: "Protetor", f: "Protetora" },
		healthFlat: { m: "Vital", f: "Vital" },
		manaFlat: { m: "Perspicaz", f: "Perspicaz" },
		lifeGainOnHitFlat: { m: "Sugador", f: "Sugadora" },
		manaGainOnHitFlat: { m: "Canalizador", f: "Canalizadora" },
		globalPhysicalDamageIncrease: { m: "Devastador", f: "Devastadora" },
		globalColdDamageIncrease: { m: "Gélido", f: "Gélida" },
		globalFireDamageIncrease: { m: "Flamejante", f: "Flamejante" },
		globalLightningDamageIncrease: { m: "Trovejante", f: "Trovejante" },
		globalVoidDamageIncrease: { m: "Abissal", f: "Abissal" },
		globalSpellDamageIncrease: { m: "Arcano", f: "Arcana" },
		globalElementalDamageWithAttacksIncrease: { m: "Primal", f: "Primal" },
		globalElementalDamageIncrease: { m: "Elemental", f: "Elemental" },
		globalMeleeDamageIncrease: { m: "Brutal", f: "Brutal" },
		itemRarityIncreasePrefix: { m: "Próspero", f: "Próspera" },
		coldDamageFlat: { m: "Glacial", f: "Glacial" },
		fireDamageFlat: { m: "Ardente", f: "Ardente" },
		lightningDamageFlat: { m: "Eletrizante", f: "Eletrizante" },
		voidDamageFlat: { m: "Vácuo-Tocado", f: "Vácuo-Tocada" },
		tomeGainAsExtraCold: { m: "Tocado pelo Gelo", f: "Tocada pelo Gelo" },
		tomeGainAsExtraFire: { m: "Página Ardente", f: "Página Ardente" },
		tomeGainAsExtraLightning: { m: "Atado à Tempestade", f: "Atada à Tempestade" },
		tomeGainAsExtraVoid: { m: "Inscrito no Abismo", f: "Inscrita no Abismo" },
		physicalDamageFlat: { m: "Pesado", f: "Pesada" },
		physicalDamageFlatGlobal: { m: "Pesado", f: "Pesada" },
		physicalDamageIncrease: { m: "Cruel", f: "Cruel" },
		coldDamageToAttacksFlat: { m: "Congelante", f: "Congelante" },
		fireDamageToAttacksFlat: { m: "Escaldante", f: "Escaldante" },
		lightningDamageToAttacksFlat: { m: "Crepitante", f: "Crepitante" },
		voidDamageToAttacksFlat: { m: "Marcado pelo Vácuo", f: "Marcada pelo Vácuo" },
		coldDamageToAttacksFlatGlobal: { m: "Congelante", f: "Congelante" },
		fireDamageToAttacksFlatGlobal: { m: "Escaldante", f: "Escaldante" },
		lightningDamageToAttacksFlatGlobal: { m: "Crepitante", f: "Crepitante" },
		voidDamageToAttacksFlatGlobal: { m: "Marcado pelo Vácuo", f: "Marcada pelo Vácuo" },
	},
	suffixPhrases: {
		strengthFlat: "da Força",
		dexterityFlat: "da Destreza",
		intelligenceFlat: "da Inteligência",
		allAttributesFlat: "de Todos os Atributos",
		localDefenseIncrease: "da Fortificação",
		globalArmorIncrease: "da Proteção",
		globalEvasionIncrease: "da Esquiva",
		globalBarrierIncrease: "da Salvaguarda",
		healthRegenFlat: "da Regeneração",
		manaRegenFlat: "do Foco",
		lifeOnKillFlat: "do Ceifar",
		manaOnKillFlat: "da Absorção",
		thornsDamageFlat: "dos Espinhos",
		blockChanceIncrease: "do Bloqueio",
		globalAttackSpeedIncrease: "da Pressa",
		globalCastSpeedIncrease: "da Conjuração",
		globalCriticalChanceIncrease: "da Letalidade",
		itemRarityIncreaseSuffix: "da Fortuna",
		coldResistance: "da Resistência ao Frio",
		fireResistance: "da Resistência ao Fogo",
		lightningResistance: "da Resistência ao Raio",
		voidResistance: "da Resistência ao Vácuo",
		movementSpeedIncrease: "da Velocidade",
		lifeLeechPercent: "do Roubo de Vida",
		stunDurationIncrease: "do Atordoamento",
		reducedAttributeRequirements: "do Digno",
		attackSpeedIncrease: "da Rapidez",
		criticalChanceIncrease: "da Precisão",
		accuracyFlat: "do Patrulheiro",
		criticalStrikeMultiplierFlat: "da Destruição",
	},
	rareFirstWords: ["Lâmina", "Coroa", "Marca", "Garra", "Ruína", "Tempestade", "Sombra", "Cinzas", "Fúria", "Pavor", "Vazio", "Destino", "Alma", "Morte", "Lúgubre", "Mente", "Dragão", "Águia", "Fênix", "Runa", "Víbora", "Kraken", "Estrago", "Vendaval", "Crepúsculo", "Sangue", "Ira", "Espírito", "Praga", "Espinho"],
	rareSecondWords: ["da Tempestade", "do Vazio", "das Sombras", "do Dragão", "da Praga", "da Ruína", "do Sangue", "do Crepúsculo", "da Fúria", "do Abismo", "da Morte", "do Trovão", "da Lâmina", "das Cinzas", "do Espírito", "do Caçador", "da Águia", "do Lobo", "da Serpente", "da Coroa", "do Vento", "da Aurora", "do Ocaso", "do Pavor", "do Inverno", "do Vulcão", "da Noite", "da Estrela", "do Ferro", "da Tormenta"],
};
